2025-03-12 14:12:44,699 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)'))': /fleet
2025-03-12 14:12:46,721 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)'))': /fleet
2025-03-12 14:12:50,732 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)'))': /fleet
2025-03-12 14:12:58,759 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)'))': /fleet
2025-03-12 14:13:14,771 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)'))': /fleet
2025-03-12 14:13:14,783 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='api.hoppe-sts.com', port=443): Max retries exceeded with url: /fleet (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
2025-03-12 14:13:14,784 - hoppe_etl_pipeline - ERROR - Pipeline failed: Failed to get ship data
2025-03-12 14:13:14,784 - hoppe_etl_pipeline - INFO - Pipeline completed in 0:00:39.887003
2025-03-12 14:40:29,292 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/ShipData.json
2025-03-12 14:40:29,378 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/ShipData.parquet
2025-03-12 14:40:29,383 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/ShipData_main_engines.parquet
2025-03-12 14:40:29,386 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/ShipData_aux_engines.parquet
2025-03-12 14:40:36,123 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9400071.json
2025-03-12 14:40:36,137 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9400071.parquet
2025-03-12 14:40:36,380 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9725512.json
2025-03-12 14:40:36,388 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9725512.parquet
2025-03-12 14:40:36,581 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9725524.json
2025-03-12 14:40:36,589 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9725524.parquet
2025-03-12 14:40:36,710 - hoppe_etl_pipeline - ERROR - API request failed: 404 Client Error: Not Found for url: https://api.hoppe-sts.com/fleet/9778399/signals
2025-03-12 14:40:36,868 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9696826.json
2025-03-12 14:40:36,879 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9696826.parquet
2025-03-12 14:40:37,064 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9693290.json
2025-03-12 14:40:37,071 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9693290.parquet
2025-03-12 14:40:37,308 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9306184.json
2025-03-12 14:40:37,318 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9306184.parquet
2025-03-12 14:40:37,544 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9693331.json
2025-03-12 14:40:37,566 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9693331.parquet
2025-03-12 14:40:37,823 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9306287.json
2025-03-12 14:40:37,833 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9306287.parquet
2025-03-12 14:40:38,252 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9306160.json
2025-03-12 14:40:38,263 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9306160.parquet
2025-03-12 14:40:38,499 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9696838.json
2025-03-12 14:40:38,506 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9696838.parquet
2025-03-12 14:40:38,639 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9693329.json
2025-03-12 14:40:38,649 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9693329.parquet
2025-03-12 14:40:38,903 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9395525.json
2025-03-12 14:40:38,912 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9395525.parquet
2025-03-12 14:40:39,171 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Signals_9726566.json
2025-03-12 14:40:39,181 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Signals_9726566.parquet
2025-03-12 14:40:40,269 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Timeseries_9696826.json
2025-03-12 14:40:40,311 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Timeseries_9306184.json
2025-03-12 14:40:40,448 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9696826
2025-03-12 14:40:40,457 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Timeseries_9696826.parquet
2025-03-12 14:40:40,475 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306184
2025-03-12 14:40:40,489 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Timeseries_9306184.parquet
2025-03-12 14:40:40,786 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/13/40/Gaps_9306184.parquet
2025-03-12 14:40:41,031 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/13/40/Gaps_9696826.parquet
2025-03-12 14:40:41,749 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Timeseries_9696838.json
2025-03-12 14:40:41,810 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9696838
2025-03-12 14:40:41,817 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Timeseries_9696838.parquet
2025-03-12 14:40:41,891 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/13/40/Gaps_9696838.parquet
2025-03-12 14:40:44,171 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/0071ec5d-eb42-431b-b6f8-dadd481c5307.json?AWSAccessKeyId=ASIAU3FAITLP6YC4SI2C&Signature=nzVm4V6fdl3V9x4t%2Fqk9%2BCHAxks%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJHMEUCIQCLjwbhXxM8UY2sy4UehiD6N5PPhHTgqPLGdZigjq00ZQIgRf7fUYeyNS9jrskp%2By6ZZ1dhHyicwXp2gp4geU9cbMYqjwMIvv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDK961ALeO2no0imVKirjApuV0BFi9vOQU6xHzTQIwD6Ua1Wx%2FK%2FpfuRrjF6FkFa306CbdOg2PVLUINTs9otrHtFQExa35GdJxhhICuJinThaW6OHjKxvpR8E%2F8XQoziN0SDA3UK9PgnwFzPrdf3a1%2FAW2h3%2Bh75gFABS3wyBaX2c7kJ0JxlSZoGUnBE6ev2MOH%2BR6QEl67UMiPpzKViNKypBU0JM5F8DZa8AGY3iT%2BLkwIsFXWRFWtMFbPPr4ylp4p01a8qwZZepqhYg5yWrjp1sa0zpHzRF6xUa9x5QEaDsworTf7zzCTtWJi%2FeCUG4sXjjs8F6so5nS7SaiejETVmJXbVkPAafkBLi4qRBfA0uDljmqEe87%2FU8CzD9Eg%2F4eCzO14iX3lMail%2FRfvJ5byo8e6uEc1ZnJry3rUZfIZC3pmjSUSpXHQTSFeC8CE3xHE5dcrRy0afzfP0inM8QlA0ttUoC4E%2B7St%2Bg2gVxxSfeY9Iw5YjGvgY6ngHgclcOzhn8z7JKDHr33zev0DNdxs8xJuaTMFPW8mkqIbq2nt9wM1yqEbjD6PKQuPhAb7nJqQUsLE9Kl2dHYnItLWG1FacFZ1Nt8BhxWFqguqn523zmYgMFNZ2RZpX5xMIe%2BNbF7yEQKcQUPk3SjnKMOC4DFEybqqvOYcpowSbR%2B2mUTmJm6lRfmxn3s2lU9lQaBLJ7xOl8CaHZbkB4Ug%3D%3D&Expires=1741787443
2025-03-12 14:40:46,233 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/0071ec5d-eb42-431b-b6f8-dadd481c5307.json?AWSAccessKeyId=ASIAU3FAITLP6YC4SI2C&Signature=nzVm4V6fdl3V9x4t%2Fqk9%2BCHAxks%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJHMEUCIQCLjwbhXxM8UY2sy4UehiD6N5PPhHTgqPLGdZigjq00ZQIgRf7fUYeyNS9jrskp%2By6ZZ1dhHyicwXp2gp4geU9cbMYqjwMIvv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDK961ALeO2no0imVKirjApuV0BFi9vOQU6xHzTQIwD6Ua1Wx%2FK%2FpfuRrjF6FkFa306CbdOg2PVLUINTs9otrHtFQExa35GdJxhhICuJinThaW6OHjKxvpR8E%2F8XQoziN0SDA3UK9PgnwFzPrdf3a1%2FAW2h3%2Bh75gFABS3wyBaX2c7kJ0JxlSZoGUnBE6ev2MOH%2BR6QEl67UMiPpzKViNKypBU0JM5F8DZa8AGY3iT%2BLkwIsFXWRFWtMFbPPr4ylp4p01a8qwZZepqhYg5yWrjp1sa0zpHzRF6xUa9x5QEaDsworTf7zzCTtWJi%2FeCUG4sXjjs8F6so5nS7SaiejETVmJXbVkPAafkBLi4qRBfA0uDljmqEe87%2FU8CzD9Eg%2F4eCzO14iX3lMail%2FRfvJ5byo8e6uEc1ZnJry3rUZfIZC3pmjSUSpXHQTSFeC8CE3xHE5dcrRy0afzfP0inM8QlA0ttUoC4E%2B7St%2Bg2gVxxSfeY9Iw5YjGvgY6ngHgclcOzhn8z7JKDHr33zev0DNdxs8xJuaTMFPW8mkqIbq2nt9wM1yqEbjD6PKQuPhAb7nJqQUsLE9Kl2dHYnItLWG1FacFZ1Nt8BhxWFqguqn523zmYgMFNZ2RZpX5xMIe%2BNbF7yEQKcQUPk3SjnKMOC4DFEybqqvOYcpowSbR%2B2mUTmJm6lRfmxn3s2lU9lQaBLJ7xOl8CaHZbkB4Ug%3D%3D&Expires=1741787443
2025-03-12 14:40:46,941 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b8d635be-1c94-4e79-bdb6-3040246ad2d5.json?AWSAccessKeyId=ASIAU3FAITLPRDWQI5KI&Signature=bDYsfz3cQ6%2FR0pfOnR7vR89HOyE%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJGMEQCIHLG2bjSfg3rMh4uP8MeemV9OZ%2FbdrD0k9zrzdS92QMqAiB0R54S2x2F2%2BsWmsjxz2PHRwa7Q5rLybU5KVJyqsd0JSqPAwi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDMzMzE5NjA3MzY5NSIMslsEH05AC5MGJiF7KuMCoQpTVI2gN60WLRKjTO93VEYTQ0VCEGQyPJ6gIGd2g7dSB0suQBtU8MkQ2yaYqRELUf7wZpAeZy97pRrmu5tsEboeuhEeWKmSFFdhdyxihAueLq5pihCgz9FqqxD4R1SZmDF3Py6GWu5wYVuTy6whBx2i2A8Zngi837IU4vtfl%2FPg5RDiinkXBZ1sPULMeLusoLEA6FL8mExJ2JZ9rLnZmmSaJMyMbikhzxI9GXY78jyVfWeKqSzC8HU4HwXsEM5AVOfkuBmF02tC8%2F3whrenc0KgwpMOKAY1BJed3rtDyvafRgWDBguHQp1YOsBJ9edO%2FjVXS1xAoeeoS34EMSPi6xAQEUTObI9DUYunj1U6fxD5v8KtLWuEiyCAacQTpRlqDB0HZCTKh9f6WEWMihbiAHw6OzrCznxF0C7AUsHUBHXmIwxV8%2BKiAliZXwBUKHhzPGeA3K44bJVse%2FaTPmSZeMfYCDDliMa%2BBjqfASaO6%2BjMPxHcTfz5GksGkqnwrvl3m2naFI%2FXd5qgJJxICj%2Fx5w6xANzoIYv7hyUzZK2DlJvYSCGMrQYjfNfVjuvBkWSzehdEFzaYn1FjanhIfbBnyctiWy1n9un3DYlpW8RN3yKZ9y47OnYXuytXtEOyT4inri2rz8f%2FBL4R3vChzGBDp3kWFuwLgClwFP2UuLBQEIJYvrdWhq4xk7vghw%3D%3D&Expires=1741787446
2025-03-12 14:40:46,975 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Timeseries_9306287.json
2025-03-12 14:40:47,079 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306287
2025-03-12 14:40:47,095 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Timeseries_9306287.parquet
2025-03-12 14:40:47,319 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/13/40/Gaps_9306287.parquet
2025-03-12 14:40:48,308 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/593bddc1-0cf2-4592-9d8e-b3d5c237b6c7.json?AWSAccessKeyId=ASIAU3FAITLP6U6WQ4PE&Signature=c9fZbmatAgPE0jYAwlZMUPUBISA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCGnIYAamIj2EbM7JpOsAGTJsDKDOMpG9rHv1x46%2FLurgIhAOMaQDbFobEDGzM7yAeB0DjiQ5qGycCuGxALZGHE%2FQYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igx%2FKXGoJsID76KGno8q4wI%2BZmxGX%2BG7eP8OquvX%2F1AFaZ6ymgA%2BePRwm1Xb4wXm2aWPnXxkAqv7JvazIxOEgJE3xz8oct4d7ZJPtstV9Ndh0m2uc6%2FzXK2zDoJUlBNbdym8y323fWU6phEiABMKrYej5IhgDZ9zk48kCakRBz3u67uy0sph36hsjZK0ZwyRivOpyIk3o4L0FmJPyOqcJ5vMLIa2QM8KsxTtfVxg12m5xG5MCFsdlu9JPYtr7jOluta47POGiQJ5QTW3wFLRNQtwFpE1HzyQMwgh5EwnPfF2Okxh0cEFSF9llbfMHyZ8OSyZgXnobvGmUc6rGI6uxXoloN3ybI1XgOoMkWam4GC277pn3HEdtPGudB6WRxcPgFLpGezdfkW5GQ1SpLzPsnTp25%2Bw3wtZznJiq%2Fulehsmh4WYQjTE6JQDsDvLhzrL3P2cZFH1sdKb2Q6%2FTRl7F8gMSEw%2By3%2BfDOrSppY%2F3auujQf9MNedxr4GOp0Bi%2FAzVWMFSik0ZxW%2B1jCT68eF1IYaE5AzQqY1NQ%2FW7lIcbixGQpjyio%2BDvXLUMkr2NY70eqBY1EKUWJMhpZwRBGuz560DEczqn%2BHNIkHX3g8WtXK3lYvRAnE6IGY3mdWERGsp2%2FV2%2BobQWYRwQydCP8e6zeZXA5ve0W10rT3rQ7zRcJi0jjHGwJmfel4hKewPEkP2or0Vah0POEgsOw%3D%3D&Expires=1741787448
2025-03-12 14:40:48,317 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Timeseries_9725512.json
2025-03-12 14:40:48,352 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/13/40/Timeseries_9306160.json
2025-03-12 14:40:48,450 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9725512
2025-03-12 14:40:48,458 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Timeseries_9725512.parquet
2025-03-12 14:40:48,696 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306160
2025-03-12 14:40:48,697 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/13/40/Gaps_9725512.parquet
2025-03-12 14:40:48,704 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/13/40/Timeseries_9306160.parquet
2025-03-12 14:40:48,804 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/13/40/Gaps_9306160.parquet
2025-03-12 14:40:49,004 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b8d635be-1c94-4e79-bdb6-3040246ad2d5.json?AWSAccessKeyId=ASIAU3FAITLPRDWQI5KI&Signature=bDYsfz3cQ6%2FR0pfOnR7vR89HOyE%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJGMEQCIHLG2bjSfg3rMh4uP8MeemV9OZ%2FbdrD0k9zrzdS92QMqAiB0R54S2x2F2%2BsWmsjxz2PHRwa7Q5rLybU5KVJyqsd0JSqPAwi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDMzMzE5NjA3MzY5NSIMslsEH05AC5MGJiF7KuMCoQpTVI2gN60WLRKjTO93VEYTQ0VCEGQyPJ6gIGd2g7dSB0suQBtU8MkQ2yaYqRELUf7wZpAeZy97pRrmu5tsEboeuhEeWKmSFFdhdyxihAueLq5pihCgz9FqqxD4R1SZmDF3Py6GWu5wYVuTy6whBx2i2A8Zngi837IU4vtfl%2FPg5RDiinkXBZ1sPULMeLusoLEA6FL8mExJ2JZ9rLnZmmSaJMyMbikhzxI9GXY78jyVfWeKqSzC8HU4HwXsEM5AVOfkuBmF02tC8%2F3whrenc0KgwpMOKAY1BJed3rtDyvafRgWDBguHQp1YOsBJ9edO%2FjVXS1xAoeeoS34EMSPi6xAQEUTObI9DUYunj1U6fxD5v8KtLWuEiyCAacQTpRlqDB0HZCTKh9f6WEWMihbiAHw6OzrCznxF0C7AUsHUBHXmIwxV8%2BKiAliZXwBUKHhzPGeA3K44bJVse%2FaTPmSZeMfYCDDliMa%2BBjqfASaO6%2BjMPxHcTfz5GksGkqnwrvl3m2naFI%2FXd5qgJJxICj%2Fx5w6xANzoIYv7hyUzZK2DlJvYSCGMrQYjfNfVjuvBkWSzehdEFzaYn1FjanhIfbBnyctiWy1n9un3DYlpW8RN3yKZ9y47OnYXuytXtEOyT4inri2rz8f%2FBL4R3vChzGBDp3kWFuwLgClwFP2UuLBQEIJYvrdWhq4xk7vghw%3D%3D&Expires=1741787446
2025-03-12 14:40:49,843 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/e7b6a632-da50-41b4-8c3e-d78c18d5c4ec.json?AWSAccessKeyId=ASIAU3FAITLPQTRXZUA5&Signature=sFn9byVQnkdGJ5btBUrB1JE3jb4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCZg03U6A1z%2BKpUtmwj7ZBMAd4Jp0tlWLHVQsRpyiyF8gIhAO9nRr2HudvPAyONM88PlreBnmteKIj6rcYCX8%2F4aqYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igyr4e3XPa35O1fCvDoq4wLJnyo6z3QvG4DUgHVMJduH6%2B%2BAeeQJq6MbSuYZS%2BCm7SVEPmyiQLZX1WTav%2FvqoCmz6fFElLej6Plh26sMdLu9OtBE1CP0SAxycIbB9h0M7Dl67c9Aabyr8Ve4uONm5ef%2FycO2BxLmxiV0ZLLyll8HJI53hnM%2BmhplS7yu7G6rp4X4Cg%2FFnaabJG%2FaOjtKPGRyj9cOCn3KzgDoBBegeZEVajhhin8NK4YQsOwEh2DwbufPIpwBL%2BZEeIi%2FXLBNAS89RWe0MsuWFOkHXKEAdOUxSXvmtfuRgHiPNZa3g1dist169jNIK6rdX%2BMs59B4Mguh8pMtqcQH5wV9efScy8U8NxgCPWlPFJm%2FNGvm%2FMp4zgo05CpmSwGoUjC7phuMjA1htpSPt%2Fof7XDeeLUtlojZQtOvNtKaxTXIzi4dISsDVTDyFckvP1S2lFZEAimDqp%2FIr%2BwEhPW%2FJoOmOdRuZxy3BXj4MNedxr4GOp0BRbM1ASjhD6fBir5ykiv4zOXQ%2BkZlnAe5J1PzxVpa2GiiV%2B7%2BusZgObDEi%2BSOuTwlQ%2FzPbkMJXZQSi5Cg2ouDw%2BUeWc3UX%2FCmRdA%2FG0Jhjh%2Bn1bGnFU%2FOyd%2BJD3fz%2FlaWm8a3TppVgynz9V%2B2tqXEuqcmQAKQjjMQ9lHYdvigbk9lFRnhh%2BWA3MXzgKmcSRsyZt5YE2tp%2FgH6Z66BZw%3D%3D&Expires=1741787449
2025-03-12 14:40:50,291 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/0071ec5d-eb42-431b-b6f8-dadd481c5307.json?AWSAccessKeyId=ASIAU3FAITLP6YC4SI2C&Signature=nzVm4V6fdl3V9x4t%2Fqk9%2BCHAxks%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJHMEUCIQCLjwbhXxM8UY2sy4UehiD6N5PPhHTgqPLGdZigjq00ZQIgRf7fUYeyNS9jrskp%2By6ZZ1dhHyicwXp2gp4geU9cbMYqjwMIvv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDK961ALeO2no0imVKirjApuV0BFi9vOQU6xHzTQIwD6Ua1Wx%2FK%2FpfuRrjF6FkFa306CbdOg2PVLUINTs9otrHtFQExa35GdJxhhICuJinThaW6OHjKxvpR8E%2F8XQoziN0SDA3UK9PgnwFzPrdf3a1%2FAW2h3%2Bh75gFABS3wyBaX2c7kJ0JxlSZoGUnBE6ev2MOH%2BR6QEl67UMiPpzKViNKypBU0JM5F8DZa8AGY3iT%2BLkwIsFXWRFWtMFbPPr4ylp4p01a8qwZZepqhYg5yWrjp1sa0zpHzRF6xUa9x5QEaDsworTf7zzCTtWJi%2FeCUG4sXjjs8F6so5nS7SaiejETVmJXbVkPAafkBLi4qRBfA0uDljmqEe87%2FU8CzD9Eg%2F4eCzO14iX3lMail%2FRfvJ5byo8e6uEc1ZnJry3rUZfIZC3pmjSUSpXHQTSFeC8CE3xHE5dcrRy0afzfP0inM8QlA0ttUoC4E%2B7St%2Bg2gVxxSfeY9Iw5YjGvgY6ngHgclcOzhn8z7JKDHr33zev0DNdxs8xJuaTMFPW8mkqIbq2nt9wM1yqEbjD6PKQuPhAb7nJqQUsLE9Kl2dHYnItLWG1FacFZ1Nt8BhxWFqguqn523zmYgMFNZ2RZpX5xMIe%2BNbF7yEQKcQUPk3SjnKMOC4DFEybqqvOYcpowSbR%2B2mUTmJm6lRfmxn3s2lU9lQaBLJ7xOl8CaHZbkB4Ug%3D%3D&Expires=1741787443
2025-03-12 14:40:50,404 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/593bddc1-0cf2-4592-9d8e-b3d5c237b6c7.json?AWSAccessKeyId=ASIAU3FAITLP6U6WQ4PE&Signature=c9fZbmatAgPE0jYAwlZMUPUBISA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCGnIYAamIj2EbM7JpOsAGTJsDKDOMpG9rHv1x46%2FLurgIhAOMaQDbFobEDGzM7yAeB0DjiQ5qGycCuGxALZGHE%2FQYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igx%2FKXGoJsID76KGno8q4wI%2BZmxGX%2BG7eP8OquvX%2F1AFaZ6ymgA%2BePRwm1Xb4wXm2aWPnXxkAqv7JvazIxOEgJE3xz8oct4d7ZJPtstV9Ndh0m2uc6%2FzXK2zDoJUlBNbdym8y323fWU6phEiABMKrYej5IhgDZ9zk48kCakRBz3u67uy0sph36hsjZK0ZwyRivOpyIk3o4L0FmJPyOqcJ5vMLIa2QM8KsxTtfVxg12m5xG5MCFsdlu9JPYtr7jOluta47POGiQJ5QTW3wFLRNQtwFpE1HzyQMwgh5EwnPfF2Okxh0cEFSF9llbfMHyZ8OSyZgXnobvGmUc6rGI6uxXoloN3ybI1XgOoMkWam4GC277pn3HEdtPGudB6WRxcPgFLpGezdfkW5GQ1SpLzPsnTp25%2Bw3wtZznJiq%2Fulehsmh4WYQjTE6JQDsDvLhzrL3P2cZFH1sdKb2Q6%2FTRl7F8gMSEw%2By3%2BfDOrSppY%2F3auujQf9MNedxr4GOp0Bi%2FAzVWMFSik0ZxW%2B1jCT68eF1IYaE5AzQqY1NQ%2FW7lIcbixGQpjyio%2BDvXLUMkr2NY70eqBY1EKUWJMhpZwRBGuz560DEczqn%2BHNIkHX3g8WtXK3lYvRAnE6IGY3mdWERGsp2%2FV2%2BobQWYRwQydCP8e6zeZXA5ve0W10rT3rQ7zRcJi0jjHGwJmfel4hKewPEkP2or0Vah0POEgsOw%3D%3D&Expires=1741787448
2025-03-12 14:40:52,034 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/e7b6a632-da50-41b4-8c3e-d78c18d5c4ec.json?AWSAccessKeyId=ASIAU3FAITLPQTRXZUA5&Signature=sFn9byVQnkdGJ5btBUrB1JE3jb4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCZg03U6A1z%2BKpUtmwj7ZBMAd4Jp0tlWLHVQsRpyiyF8gIhAO9nRr2HudvPAyONM88PlreBnmteKIj6rcYCX8%2F4aqYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igyr4e3XPa35O1fCvDoq4wLJnyo6z3QvG4DUgHVMJduH6%2B%2BAeeQJq6MbSuYZS%2BCm7SVEPmyiQLZX1WTav%2FvqoCmz6fFElLej6Plh26sMdLu9OtBE1CP0SAxycIbB9h0M7Dl67c9Aabyr8Ve4uONm5ef%2FycO2BxLmxiV0ZLLyll8HJI53hnM%2BmhplS7yu7G6rp4X4Cg%2FFnaabJG%2FaOjtKPGRyj9cOCn3KzgDoBBegeZEVajhhin8NK4YQsOwEh2DwbufPIpwBL%2BZEeIi%2FXLBNAS89RWe0MsuWFOkHXKEAdOUxSXvmtfuRgHiPNZa3g1dist169jNIK6rdX%2BMs59B4Mguh8pMtqcQH5wV9efScy8U8NxgCPWlPFJm%2FNGvm%2FMp4zgo05CpmSwGoUjC7phuMjA1htpSPt%2Fof7XDeeLUtlojZQtOvNtKaxTXIzi4dISsDVTDyFckvP1S2lFZEAimDqp%2FIr%2BwEhPW%2FJoOmOdRuZxy3BXj4MNedxr4GOp0BRbM1ASjhD6fBir5ykiv4zOXQ%2BkZlnAe5J1PzxVpa2GiiV%2B7%2BusZgObDEi%2BSOuTwlQ%2FzPbkMJXZQSi5Cg2ouDw%2BUeWc3UX%2FCmRdA%2FG0Jhjh%2Bn1bGnFU%2FOyd%2BJD3fz%2FlaWm8a3TppVgynz9V%2B2tqXEuqcmQAKQjjMQ9lHYdvigbk9lFRnhh%2BWA3MXzgKmcSRsyZt5YE2tp%2FgH6Z66BZw%3D%3D&Expires=1741787449
2025-03-12 14:40:53,155 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b8d635be-1c94-4e79-bdb6-3040246ad2d5.json?AWSAccessKeyId=ASIAU3FAITLPRDWQI5KI&Signature=bDYsfz3cQ6%2FR0pfOnR7vR89HOyE%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJGMEQCIHLG2bjSfg3rMh4uP8MeemV9OZ%2FbdrD0k9zrzdS92QMqAiB0R54S2x2F2%2BsWmsjxz2PHRwa7Q5rLybU5KVJyqsd0JSqPAwi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDMzMzE5NjA3MzY5NSIMslsEH05AC5MGJiF7KuMCoQpTVI2gN60WLRKjTO93VEYTQ0VCEGQyPJ6gIGd2g7dSB0suQBtU8MkQ2yaYqRELUf7wZpAeZy97pRrmu5tsEboeuhEeWKmSFFdhdyxihAueLq5pihCgz9FqqxD4R1SZmDF3Py6GWu5wYVuTy6whBx2i2A8Zngi837IU4vtfl%2FPg5RDiinkXBZ1sPULMeLusoLEA6FL8mExJ2JZ9rLnZmmSaJMyMbikhzxI9GXY78jyVfWeKqSzC8HU4HwXsEM5AVOfkuBmF02tC8%2F3whrenc0KgwpMOKAY1BJed3rtDyvafRgWDBguHQp1YOsBJ9edO%2FjVXS1xAoeeoS34EMSPi6xAQEUTObI9DUYunj1U6fxD5v8KtLWuEiyCAacQTpRlqDB0HZCTKh9f6WEWMihbiAHw6OzrCznxF0C7AUsHUBHXmIwxV8%2BKiAliZXwBUKHhzPGeA3K44bJVse%2FaTPmSZeMfYCDDliMa%2BBjqfASaO6%2BjMPxHcTfz5GksGkqnwrvl3m2naFI%2FXd5qgJJxICj%2Fx5w6xANzoIYv7hyUzZK2DlJvYSCGMrQYjfNfVjuvBkWSzehdEFzaYn1FjanhIfbBnyctiWy1n9un3DYlpW8RN3yKZ9y47OnYXuytXtEOyT4inri2rz8f%2FBL4R3vChzGBDp3kWFuwLgClwFP2UuLBQEIJYvrdWhq4xk7vghw%3D%3D&Expires=1741787446
2025-03-12 14:40:54,471 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/593bddc1-0cf2-4592-9d8e-b3d5c237b6c7.json?AWSAccessKeyId=ASIAU3FAITLP6U6WQ4PE&Signature=c9fZbmatAgPE0jYAwlZMUPUBISA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCGnIYAamIj2EbM7JpOsAGTJsDKDOMpG9rHv1x46%2FLurgIhAOMaQDbFobEDGzM7yAeB0DjiQ5qGycCuGxALZGHE%2FQYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igx%2FKXGoJsID76KGno8q4wI%2BZmxGX%2BG7eP8OquvX%2F1AFaZ6ymgA%2BePRwm1Xb4wXm2aWPnXxkAqv7JvazIxOEgJE3xz8oct4d7ZJPtstV9Ndh0m2uc6%2FzXK2zDoJUlBNbdym8y323fWU6phEiABMKrYej5IhgDZ9zk48kCakRBz3u67uy0sph36hsjZK0ZwyRivOpyIk3o4L0FmJPyOqcJ5vMLIa2QM8KsxTtfVxg12m5xG5MCFsdlu9JPYtr7jOluta47POGiQJ5QTW3wFLRNQtwFpE1HzyQMwgh5EwnPfF2Okxh0cEFSF9llbfMHyZ8OSyZgXnobvGmUc6rGI6uxXoloN3ybI1XgOoMkWam4GC277pn3HEdtPGudB6WRxcPgFLpGezdfkW5GQ1SpLzPsnTp25%2Bw3wtZznJiq%2Fulehsmh4WYQjTE6JQDsDvLhzrL3P2cZFH1sdKb2Q6%2FTRl7F8gMSEw%2By3%2BfDOrSppY%2F3auujQf9MNedxr4GOp0Bi%2FAzVWMFSik0ZxW%2B1jCT68eF1IYaE5AzQqY1NQ%2FW7lIcbixGQpjyio%2BDvXLUMkr2NY70eqBY1EKUWJMhpZwRBGuz560DEczqn%2BHNIkHX3g8WtXK3lYvRAnE6IGY3mdWERGsp2%2FV2%2BobQWYRwQydCP8e6zeZXA5ve0W10rT3rQ7zRcJi0jjHGwJmfel4hKewPEkP2or0Vah0POEgsOw%3D%3D&Expires=1741787448
2025-03-12 14:40:56,100 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/e7b6a632-da50-41b4-8c3e-d78c18d5c4ec.json?AWSAccessKeyId=ASIAU3FAITLPQTRXZUA5&Signature=sFn9byVQnkdGJ5btBUrB1JE3jb4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCZg03U6A1z%2BKpUtmwj7ZBMAd4Jp0tlWLHVQsRpyiyF8gIhAO9nRr2HudvPAyONM88PlreBnmteKIj6rcYCX8%2F4aqYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igyr4e3XPa35O1fCvDoq4wLJnyo6z3QvG4DUgHVMJduH6%2B%2BAeeQJq6MbSuYZS%2BCm7SVEPmyiQLZX1WTav%2FvqoCmz6fFElLej6Plh26sMdLu9OtBE1CP0SAxycIbB9h0M7Dl67c9Aabyr8Ve4uONm5ef%2FycO2BxLmxiV0ZLLyll8HJI53hnM%2BmhplS7yu7G6rp4X4Cg%2FFnaabJG%2FaOjtKPGRyj9cOCn3KzgDoBBegeZEVajhhin8NK4YQsOwEh2DwbufPIpwBL%2BZEeIi%2FXLBNAS89RWe0MsuWFOkHXKEAdOUxSXvmtfuRgHiPNZa3g1dist169jNIK6rdX%2BMs59B4Mguh8pMtqcQH5wV9efScy8U8NxgCPWlPFJm%2FNGvm%2FMp4zgo05CpmSwGoUjC7phuMjA1htpSPt%2Fof7XDeeLUtlojZQtOvNtKaxTXIzi4dISsDVTDyFckvP1S2lFZEAimDqp%2FIr%2BwEhPW%2FJoOmOdRuZxy3BXj4MNedxr4GOp0BRbM1ASjhD6fBir5ykiv4zOXQ%2BkZlnAe5J1PzxVpa2GiiV%2B7%2BusZgObDEi%2BSOuTwlQ%2FzPbkMJXZQSi5Cg2ouDw%2BUeWc3UX%2FCmRdA%2FG0Jhjh%2Bn1bGnFU%2FOyd%2BJD3fz%2FlaWm8a3TppVgynz9V%2B2tqXEuqcmQAKQjjMQ9lHYdvigbk9lFRnhh%2BWA3MXzgKmcSRsyZt5YE2tp%2FgH6Z66BZw%3D%3D&Expires=1741787449
2025-03-12 14:40:58,448 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/0071ec5d-eb42-431b-b6f8-dadd481c5307.json?AWSAccessKeyId=ASIAU3FAITLP6YC4SI2C&Signature=nzVm4V6fdl3V9x4t%2Fqk9%2BCHAxks%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJHMEUCIQCLjwbhXxM8UY2sy4UehiD6N5PPhHTgqPLGdZigjq00ZQIgRf7fUYeyNS9jrskp%2By6ZZ1dhHyicwXp2gp4geU9cbMYqjwMIvv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDK961ALeO2no0imVKirjApuV0BFi9vOQU6xHzTQIwD6Ua1Wx%2FK%2FpfuRrjF6FkFa306CbdOg2PVLUINTs9otrHtFQExa35GdJxhhICuJinThaW6OHjKxvpR8E%2F8XQoziN0SDA3UK9PgnwFzPrdf3a1%2FAW2h3%2Bh75gFABS3wyBaX2c7kJ0JxlSZoGUnBE6ev2MOH%2BR6QEl67UMiPpzKViNKypBU0JM5F8DZa8AGY3iT%2BLkwIsFXWRFWtMFbPPr4ylp4p01a8qwZZepqhYg5yWrjp1sa0zpHzRF6xUa9x5QEaDsworTf7zzCTtWJi%2FeCUG4sXjjs8F6so5nS7SaiejETVmJXbVkPAafkBLi4qRBfA0uDljmqEe87%2FU8CzD9Eg%2F4eCzO14iX3lMail%2FRfvJ5byo8e6uEc1ZnJry3rUZfIZC3pmjSUSpXHQTSFeC8CE3xHE5dcrRy0afzfP0inM8QlA0ttUoC4E%2B7St%2Bg2gVxxSfeY9Iw5YjGvgY6ngHgclcOzhn8z7JKDHr33zev0DNdxs8xJuaTMFPW8mkqIbq2nt9wM1yqEbjD6PKQuPhAb7nJqQUsLE9Kl2dHYnItLWG1FacFZ1Nt8BhxWFqguqn523zmYgMFNZ2RZpX5xMIe%2BNbF7yEQKcQUPk3SjnKMOC4DFEybqqvOYcpowSbR%2B2mUTmJm6lRfmxn3s2lU9lQaBLJ7xOl8CaHZbkB4Ug%3D%3D&Expires=1741787443
2025-03-12 14:41:01,222 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b8d635be-1c94-4e79-bdb6-3040246ad2d5.json?AWSAccessKeyId=ASIAU3FAITLPRDWQI5KI&Signature=bDYsfz3cQ6%2FR0pfOnR7vR89HOyE%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJGMEQCIHLG2bjSfg3rMh4uP8MeemV9OZ%2FbdrD0k9zrzdS92QMqAiB0R54S2x2F2%2BsWmsjxz2PHRwa7Q5rLybU5KVJyqsd0JSqPAwi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDMzMzE5NjA3MzY5NSIMslsEH05AC5MGJiF7KuMCoQpTVI2gN60WLRKjTO93VEYTQ0VCEGQyPJ6gIGd2g7dSB0suQBtU8MkQ2yaYqRELUf7wZpAeZy97pRrmu5tsEboeuhEeWKmSFFdhdyxihAueLq5pihCgz9FqqxD4R1SZmDF3Py6GWu5wYVuTy6whBx2i2A8Zngi837IU4vtfl%2FPg5RDiinkXBZ1sPULMeLusoLEA6FL8mExJ2JZ9rLnZmmSaJMyMbikhzxI9GXY78jyVfWeKqSzC8HU4HwXsEM5AVOfkuBmF02tC8%2F3whrenc0KgwpMOKAY1BJed3rtDyvafRgWDBguHQp1YOsBJ9edO%2FjVXS1xAoeeoS34EMSPi6xAQEUTObI9DUYunj1U6fxD5v8KtLWuEiyCAacQTpRlqDB0HZCTKh9f6WEWMihbiAHw6OzrCznxF0C7AUsHUBHXmIwxV8%2BKiAliZXwBUKHhzPGeA3K44bJVse%2FaTPmSZeMfYCDDliMa%2BBjqfASaO6%2BjMPxHcTfz5GksGkqnwrvl3m2naFI%2FXd5qgJJxICj%2Fx5w6xANzoIYv7hyUzZK2DlJvYSCGMrQYjfNfVjuvBkWSzehdEFzaYn1FjanhIfbBnyctiWy1n9un3DYlpW8RN3yKZ9y47OnYXuytXtEOyT4inri2rz8f%2FBL4R3vChzGBDp3kWFuwLgClwFP2UuLBQEIJYvrdWhq4xk7vghw%3D%3D&Expires=1741787446
2025-03-12 14:41:02,613 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/593bddc1-0cf2-4592-9d8e-b3d5c237b6c7.json?AWSAccessKeyId=ASIAU3FAITLP6U6WQ4PE&Signature=c9fZbmatAgPE0jYAwlZMUPUBISA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCGnIYAamIj2EbM7JpOsAGTJsDKDOMpG9rHv1x46%2FLurgIhAOMaQDbFobEDGzM7yAeB0DjiQ5qGycCuGxALZGHE%2FQYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igx%2FKXGoJsID76KGno8q4wI%2BZmxGX%2BG7eP8OquvX%2F1AFaZ6ymgA%2BePRwm1Xb4wXm2aWPnXxkAqv7JvazIxOEgJE3xz8oct4d7ZJPtstV9Ndh0m2uc6%2FzXK2zDoJUlBNbdym8y323fWU6phEiABMKrYej5IhgDZ9zk48kCakRBz3u67uy0sph36hsjZK0ZwyRivOpyIk3o4L0FmJPyOqcJ5vMLIa2QM8KsxTtfVxg12m5xG5MCFsdlu9JPYtr7jOluta47POGiQJ5QTW3wFLRNQtwFpE1HzyQMwgh5EwnPfF2Okxh0cEFSF9llbfMHyZ8OSyZgXnobvGmUc6rGI6uxXoloN3ybI1XgOoMkWam4GC277pn3HEdtPGudB6WRxcPgFLpGezdfkW5GQ1SpLzPsnTp25%2Bw3wtZznJiq%2Fulehsmh4WYQjTE6JQDsDvLhzrL3P2cZFH1sdKb2Q6%2FTRl7F8gMSEw%2By3%2BfDOrSppY%2F3auujQf9MNedxr4GOp0Bi%2FAzVWMFSik0ZxW%2B1jCT68eF1IYaE5AzQqY1NQ%2FW7lIcbixGQpjyio%2BDvXLUMkr2NY70eqBY1EKUWJMhpZwRBGuz560DEczqn%2BHNIkHX3g8WtXK3lYvRAnE6IGY3mdWERGsp2%2FV2%2BobQWYRwQydCP8e6zeZXA5ve0W10rT3rQ7zRcJi0jjHGwJmfel4hKewPEkP2or0Vah0POEgsOw%3D%3D&Expires=1741787448
2025-03-12 14:41:04,228 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/e7b6a632-da50-41b4-8c3e-d78c18d5c4ec.json?AWSAccessKeyId=ASIAU3FAITLPQTRXZUA5&Signature=sFn9byVQnkdGJ5btBUrB1JE3jb4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCZg03U6A1z%2BKpUtmwj7ZBMAd4Jp0tlWLHVQsRpyiyF8gIhAO9nRr2HudvPAyONM88PlreBnmteKIj6rcYCX8%2F4aqYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igyr4e3XPa35O1fCvDoq4wLJnyo6z3QvG4DUgHVMJduH6%2B%2BAeeQJq6MbSuYZS%2BCm7SVEPmyiQLZX1WTav%2FvqoCmz6fFElLej6Plh26sMdLu9OtBE1CP0SAxycIbB9h0M7Dl67c9Aabyr8Ve4uONm5ef%2FycO2BxLmxiV0ZLLyll8HJI53hnM%2BmhplS7yu7G6rp4X4Cg%2FFnaabJG%2FaOjtKPGRyj9cOCn3KzgDoBBegeZEVajhhin8NK4YQsOwEh2DwbufPIpwBL%2BZEeIi%2FXLBNAS89RWe0MsuWFOkHXKEAdOUxSXvmtfuRgHiPNZa3g1dist169jNIK6rdX%2BMs59B4Mguh8pMtqcQH5wV9efScy8U8NxgCPWlPFJm%2FNGvm%2FMp4zgo05CpmSwGoUjC7phuMjA1htpSPt%2Fof7XDeeLUtlojZQtOvNtKaxTXIzi4dISsDVTDyFckvP1S2lFZEAimDqp%2FIr%2BwEhPW%2FJoOmOdRuZxy3BXj4MNedxr4GOp0BRbM1ASjhD6fBir5ykiv4zOXQ%2BkZlnAe5J1PzxVpa2GiiV%2B7%2BusZgObDEi%2BSOuTwlQ%2FzPbkMJXZQSi5Cg2ouDw%2BUeWc3UX%2FCmRdA%2FG0Jhjh%2Bn1bGnFU%2FOyd%2BJD3fz%2FlaWm8a3TppVgynz9V%2B2tqXEuqcmQAKQjjMQ9lHYdvigbk9lFRnhh%2BWA3MXzgKmcSRsyZt5YE2tp%2FgH6Z66BZw%3D%3D&Expires=1741787449
2025-03-12 14:41:14,508 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/0071ec5d-eb42-431b-b6f8-dadd481c5307.json?AWSAccessKeyId=ASIAU3FAITLP6YC4SI2C&Signature=nzVm4V6fdl3V9x4t%2Fqk9%2BCHAxks%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJHMEUCIQCLjwbhXxM8UY2sy4UehiD6N5PPhHTgqPLGdZigjq00ZQIgRf7fUYeyNS9jrskp%2By6ZZ1dhHyicwXp2gp4geU9cbMYqjwMIvv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDK961ALeO2no0imVKirjApuV0BFi9vOQU6xHzTQIwD6Ua1Wx%2FK%2FpfuRrjF6FkFa306CbdOg2PVLUINTs9otrHtFQExa35GdJxhhICuJinThaW6OHjKxvpR8E%2F8XQoziN0SDA3UK9PgnwFzPrdf3a1%2FAW2h3%2Bh75gFABS3wyBaX2c7kJ0JxlSZoGUnBE6ev2MOH%2BR6QEl67UMiPpzKViNKypBU0JM5F8DZa8AGY3iT%2BLkwIsFXWRFWtMFbPPr4ylp4p01a8qwZZepqhYg5yWrjp1sa0zpHzRF6xUa9x5QEaDsworTf7zzCTtWJi%2FeCUG4sXjjs8F6so5nS7SaiejETVmJXbVkPAafkBLi4qRBfA0uDljmqEe87%2FU8CzD9Eg%2F4eCzO14iX3lMail%2FRfvJ5byo8e6uEc1ZnJry3rUZfIZC3pmjSUSpXHQTSFeC8CE3xHE5dcrRy0afzfP0inM8QlA0ttUoC4E%2B7St%2Bg2gVxxSfeY9Iw5YjGvgY6ngHgclcOzhn8z7JKDHr33zev0DNdxs8xJuaTMFPW8mkqIbq2nt9wM1yqEbjD6PKQuPhAb7nJqQUsLE9Kl2dHYnItLWG1FacFZ1Nt8BhxWFqguqn523zmYgMFNZ2RZpX5xMIe%2BNbF7yEQKcQUPk3SjnKMOC4DFEybqqvOYcpowSbR%2B2mUTmJm6lRfmxn3s2lU9lQaBLJ7xOl8CaHZbkB4Ug%3D%3D&Expires=1741787443
2025-03-12 14:41:14,647 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9726566/0071ec5d-eb42-431b-b6f8-dadd481c5307.json?AWSAccessKeyId=ASIAU3FAITLP6YC4SI2C&Signature=nzVm4V6fdl3V9x4t%2Fqk9%2BCHAxks%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJHMEUCIQCLjwbhXxM8UY2sy4UehiD6N5PPhHTgqPLGdZigjq00ZQIgRf7fUYeyNS9jrskp%2By6ZZ1dhHyicwXp2gp4geU9cbMYqjwMIvv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDK961ALeO2no0imVKirjApuV0BFi9vOQU6xHzTQIwD6Ua1Wx%2FK%2FpfuRrjF6FkFa306CbdOg2PVLUINTs9otrHtFQExa35GdJxhhICuJinThaW6OHjKxvpR8E%2F8XQoziN0SDA3UK9PgnwFzPrdf3a1%2FAW2h3%2Bh75gFABS3wyBaX2c7kJ0JxlSZoGUnBE6ev2MOH%2BR6QEl67UMiPpzKViNKypBU0JM5F8DZa8AGY3iT%2BLkwIsFXWRFWtMFbPPr4ylp4p01a8qwZZepqhYg5yWrjp1sa0zpHzRF6xUa9x5QEaDsworTf7zzCTtWJi%2FeCUG4sXjjs8F6so5nS7SaiejETVmJXbVkPAafkBLi4qRBfA0uDljmqEe87%2FU8CzD9Eg%2F4eCzO14iX3lMail%2FRfvJ5byo8e6uEc1ZnJry3rUZfIZC3pmjSUSpXHQTSFeC8CE3xHE5dcrRy0afzfP0inM8QlA0ttUoC4E%2B7St%2Bg2gVxxSfeY9Iw5YjGvgY6ngHgclcOzhn8z7JKDHr33zev0DNdxs8xJuaTMFPW8mkqIbq2nt9wM1yqEbjD6PKQuPhAb7nJqQUsLE9Kl2dHYnItLWG1FacFZ1Nt8BhxWFqguqn523zmYgMFNZ2RZpX5xMIe%2BNbF7yEQKcQUPk3SjnKMOC4DFEybqqvOYcpowSbR%2B2mUTmJm6lRfmxn3s2lU9lQaBLJ7xOl8CaHZbkB4Ug%3D%3D&Expires=1741787443 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 14:41:17,352 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b8d635be-1c94-4e79-bdb6-3040246ad2d5.json?AWSAccessKeyId=ASIAU3FAITLPRDWQI5KI&Signature=bDYsfz3cQ6%2FR0pfOnR7vR89HOyE%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJGMEQCIHLG2bjSfg3rMh4uP8MeemV9OZ%2FbdrD0k9zrzdS92QMqAiB0R54S2x2F2%2BsWmsjxz2PHRwa7Q5rLybU5KVJyqsd0JSqPAwi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDMzMzE5NjA3MzY5NSIMslsEH05AC5MGJiF7KuMCoQpTVI2gN60WLRKjTO93VEYTQ0VCEGQyPJ6gIGd2g7dSB0suQBtU8MkQ2yaYqRELUf7wZpAeZy97pRrmu5tsEboeuhEeWKmSFFdhdyxihAueLq5pihCgz9FqqxD4R1SZmDF3Py6GWu5wYVuTy6whBx2i2A8Zngi837IU4vtfl%2FPg5RDiinkXBZ1sPULMeLusoLEA6FL8mExJ2JZ9rLnZmmSaJMyMbikhzxI9GXY78jyVfWeKqSzC8HU4HwXsEM5AVOfkuBmF02tC8%2F3whrenc0KgwpMOKAY1BJed3rtDyvafRgWDBguHQp1YOsBJ9edO%2FjVXS1xAoeeoS34EMSPi6xAQEUTObI9DUYunj1U6fxD5v8KtLWuEiyCAacQTpRlqDB0HZCTKh9f6WEWMihbiAHw6OzrCznxF0C7AUsHUBHXmIwxV8%2BKiAliZXwBUKHhzPGeA3K44bJVse%2FaTPmSZeMfYCDDliMa%2BBjqfASaO6%2BjMPxHcTfz5GksGkqnwrvl3m2naFI%2FXd5qgJJxICj%2Fx5w6xANzoIYv7hyUzZK2DlJvYSCGMrQYjfNfVjuvBkWSzehdEFzaYn1FjanhIfbBnyctiWy1n9un3DYlpW8RN3yKZ9y47OnYXuytXtEOyT4inri2rz8f%2FBL4R3vChzGBDp3kWFuwLgClwFP2UuLBQEIJYvrdWhq4xk7vghw%3D%3D&Expires=1741787446
2025-03-12 14:41:17,489 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9693329/b8d635be-1c94-4e79-bdb6-3040246ad2d5.json?AWSAccessKeyId=ASIAU3FAITLPRDWQI5KI&Signature=bDYsfz3cQ6%2FR0pfOnR7vR89HOyE%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHUaCWV1LXdlc3QtMSJGMEQCIHLG2bjSfg3rMh4uP8MeemV9OZ%2FbdrD0k9zrzdS92QMqAiB0R54S2x2F2%2BsWmsjxz2PHRwa7Q5rLybU5KVJyqsd0JSqPAwi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDMzMzE5NjA3MzY5NSIMslsEH05AC5MGJiF7KuMCoQpTVI2gN60WLRKjTO93VEYTQ0VCEGQyPJ6gIGd2g7dSB0suQBtU8MkQ2yaYqRELUf7wZpAeZy97pRrmu5tsEboeuhEeWKmSFFdhdyxihAueLq5pihCgz9FqqxD4R1SZmDF3Py6GWu5wYVuTy6whBx2i2A8Zngi837IU4vtfl%2FPg5RDiinkXBZ1sPULMeLusoLEA6FL8mExJ2JZ9rLnZmmSaJMyMbikhzxI9GXY78jyVfWeKqSzC8HU4HwXsEM5AVOfkuBmF02tC8%2F3whrenc0KgwpMOKAY1BJed3rtDyvafRgWDBguHQp1YOsBJ9edO%2FjVXS1xAoeeoS34EMSPi6xAQEUTObI9DUYunj1U6fxD5v8KtLWuEiyCAacQTpRlqDB0HZCTKh9f6WEWMihbiAHw6OzrCznxF0C7AUsHUBHXmIwxV8%2BKiAliZXwBUKHhzPGeA3K44bJVse%2FaTPmSZeMfYCDDliMa%2BBjqfASaO6%2BjMPxHcTfz5GksGkqnwrvl3m2naFI%2FXd5qgJJxICj%2Fx5w6xANzoIYv7hyUzZK2DlJvYSCGMrQYjfNfVjuvBkWSzehdEFzaYn1FjanhIfbBnyctiWy1n9un3DYlpW8RN3yKZ9y47OnYXuytXtEOyT4inri2rz8f%2FBL4R3vChzGBDp3kWFuwLgClwFP2UuLBQEIJYvrdWhq4xk7vghw%3D%3D&Expires=1741787446 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 14:41:18,674 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/593bddc1-0cf2-4592-9d8e-b3d5c237b6c7.json?AWSAccessKeyId=ASIAU3FAITLP6U6WQ4PE&Signature=c9fZbmatAgPE0jYAwlZMUPUBISA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCGnIYAamIj2EbM7JpOsAGTJsDKDOMpG9rHv1x46%2FLurgIhAOMaQDbFobEDGzM7yAeB0DjiQ5qGycCuGxALZGHE%2FQYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igx%2FKXGoJsID76KGno8q4wI%2BZmxGX%2BG7eP8OquvX%2F1AFaZ6ymgA%2BePRwm1Xb4wXm2aWPnXxkAqv7JvazIxOEgJE3xz8oct4d7ZJPtstV9Ndh0m2uc6%2FzXK2zDoJUlBNbdym8y323fWU6phEiABMKrYej5IhgDZ9zk48kCakRBz3u67uy0sph36hsjZK0ZwyRivOpyIk3o4L0FmJPyOqcJ5vMLIa2QM8KsxTtfVxg12m5xG5MCFsdlu9JPYtr7jOluta47POGiQJ5QTW3wFLRNQtwFpE1HzyQMwgh5EwnPfF2Okxh0cEFSF9llbfMHyZ8OSyZgXnobvGmUc6rGI6uxXoloN3ybI1XgOoMkWam4GC277pn3HEdtPGudB6WRxcPgFLpGezdfkW5GQ1SpLzPsnTp25%2Bw3wtZznJiq%2Fulehsmh4WYQjTE6JQDsDvLhzrL3P2cZFH1sdKb2Q6%2FTRl7F8gMSEw%2By3%2BfDOrSppY%2F3auujQf9MNedxr4GOp0Bi%2FAzVWMFSik0ZxW%2B1jCT68eF1IYaE5AzQqY1NQ%2FW7lIcbixGQpjyio%2BDvXLUMkr2NY70eqBY1EKUWJMhpZwRBGuz560DEczqn%2BHNIkHX3g8WtXK3lYvRAnE6IGY3mdWERGsp2%2FV2%2BobQWYRwQydCP8e6zeZXA5ve0W10rT3rQ7zRcJi0jjHGwJmfel4hKewPEkP2or0Vah0POEgsOw%3D%3D&Expires=1741787448
2025-03-12 14:41:18,739 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9693290/593bddc1-0cf2-4592-9d8e-b3d5c237b6c7.json?AWSAccessKeyId=ASIAU3FAITLP6U6WQ4PE&Signature=c9fZbmatAgPE0jYAwlZMUPUBISA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCGnIYAamIj2EbM7JpOsAGTJsDKDOMpG9rHv1x46%2FLurgIhAOMaQDbFobEDGzM7yAeB0DjiQ5qGycCuGxALZGHE%2FQYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igx%2FKXGoJsID76KGno8q4wI%2BZmxGX%2BG7eP8OquvX%2F1AFaZ6ymgA%2BePRwm1Xb4wXm2aWPnXxkAqv7JvazIxOEgJE3xz8oct4d7ZJPtstV9Ndh0m2uc6%2FzXK2zDoJUlBNbdym8y323fWU6phEiABMKrYej5IhgDZ9zk48kCakRBz3u67uy0sph36hsjZK0ZwyRivOpyIk3o4L0FmJPyOqcJ5vMLIa2QM8KsxTtfVxg12m5xG5MCFsdlu9JPYtr7jOluta47POGiQJ5QTW3wFLRNQtwFpE1HzyQMwgh5EwnPfF2Okxh0cEFSF9llbfMHyZ8OSyZgXnobvGmUc6rGI6uxXoloN3ybI1XgOoMkWam4GC277pn3HEdtPGudB6WRxcPgFLpGezdfkW5GQ1SpLzPsnTp25%2Bw3wtZznJiq%2Fulehsmh4WYQjTE6JQDsDvLhzrL3P2cZFH1sdKb2Q6%2FTRl7F8gMSEw%2By3%2BfDOrSppY%2F3auujQf9MNedxr4GOp0Bi%2FAzVWMFSik0ZxW%2B1jCT68eF1IYaE5AzQqY1NQ%2FW7lIcbixGQpjyio%2BDvXLUMkr2NY70eqBY1EKUWJMhpZwRBGuz560DEczqn%2BHNIkHX3g8WtXK3lYvRAnE6IGY3mdWERGsp2%2FV2%2BobQWYRwQydCP8e6zeZXA5ve0W10rT3rQ7zRcJi0jjHGwJmfel4hKewPEkP2or0Vah0POEgsOw%3D%3D&Expires=1741787448 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 14:41:20,379 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/e7b6a632-da50-41b4-8c3e-d78c18d5c4ec.json?AWSAccessKeyId=ASIAU3FAITLPQTRXZUA5&Signature=sFn9byVQnkdGJ5btBUrB1JE3jb4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCZg03U6A1z%2BKpUtmwj7ZBMAd4Jp0tlWLHVQsRpyiyF8gIhAO9nRr2HudvPAyONM88PlreBnmteKIj6rcYCX8%2F4aqYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igyr4e3XPa35O1fCvDoq4wLJnyo6z3QvG4DUgHVMJduH6%2B%2BAeeQJq6MbSuYZS%2BCm7SVEPmyiQLZX1WTav%2FvqoCmz6fFElLej6Plh26sMdLu9OtBE1CP0SAxycIbB9h0M7Dl67c9Aabyr8Ve4uONm5ef%2FycO2BxLmxiV0ZLLyll8HJI53hnM%2BmhplS7yu7G6rp4X4Cg%2FFnaabJG%2FaOjtKPGRyj9cOCn3KzgDoBBegeZEVajhhin8NK4YQsOwEh2DwbufPIpwBL%2BZEeIi%2FXLBNAS89RWe0MsuWFOkHXKEAdOUxSXvmtfuRgHiPNZa3g1dist169jNIK6rdX%2BMs59B4Mguh8pMtqcQH5wV9efScy8U8NxgCPWlPFJm%2FNGvm%2FMp4zgo05CpmSwGoUjC7phuMjA1htpSPt%2Fof7XDeeLUtlojZQtOvNtKaxTXIzi4dISsDVTDyFckvP1S2lFZEAimDqp%2FIr%2BwEhPW%2FJoOmOdRuZxy3BXj4MNedxr4GOp0BRbM1ASjhD6fBir5ykiv4zOXQ%2BkZlnAe5J1PzxVpa2GiiV%2B7%2BusZgObDEi%2BSOuTwlQ%2FzPbkMJXZQSi5Cg2ouDw%2BUeWc3UX%2FCmRdA%2FG0Jhjh%2Bn1bGnFU%2FOyd%2BJD3fz%2FlaWm8a3TppVgynz9V%2B2tqXEuqcmQAKQjjMQ9lHYdvigbk9lFRnhh%2BWA3MXzgKmcSRsyZt5YE2tp%2FgH6Z66BZw%3D%3D&Expires=1741787449
2025-03-12 14:41:20,521 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9725524/e7b6a632-da50-41b4-8c3e-d78c18d5c4ec.json?AWSAccessKeyId=ASIAU3FAITLPQTRXZUA5&Signature=sFn9byVQnkdGJ5btBUrB1JE3jb4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJIMEYCIQCZg03U6A1z%2BKpUtmwj7ZBMAd4Jp0tlWLHVQsRpyiyF8gIhAO9nRr2HudvPAyONM88PlreBnmteKIj6rcYCX8%2F4aqYVKo8DCL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igyr4e3XPa35O1fCvDoq4wLJnyo6z3QvG4DUgHVMJduH6%2B%2BAeeQJq6MbSuYZS%2BCm7SVEPmyiQLZX1WTav%2FvqoCmz6fFElLej6Plh26sMdLu9OtBE1CP0SAxycIbB9h0M7Dl67c9Aabyr8Ve4uONm5ef%2FycO2BxLmxiV0ZLLyll8HJI53hnM%2BmhplS7yu7G6rp4X4Cg%2FFnaabJG%2FaOjtKPGRyj9cOCn3KzgDoBBegeZEVajhhin8NK4YQsOwEh2DwbufPIpwBL%2BZEeIi%2FXLBNAS89RWe0MsuWFOkHXKEAdOUxSXvmtfuRgHiPNZa3g1dist169jNIK6rdX%2BMs59B4Mguh8pMtqcQH5wV9efScy8U8NxgCPWlPFJm%2FNGvm%2FMp4zgo05CpmSwGoUjC7phuMjA1htpSPt%2Fof7XDeeLUtlojZQtOvNtKaxTXIzi4dISsDVTDyFckvP1S2lFZEAimDqp%2FIr%2BwEhPW%2FJoOmOdRuZxy3BXj4MNedxr4GOp0BRbM1ASjhD6fBir5ykiv4zOXQ%2BkZlnAe5J1PzxVpa2GiiV%2B7%2BusZgObDEi%2BSOuTwlQ%2FzPbkMJXZQSi5Cg2ouDw%2BUeWc3UX%2FCmRdA%2FG0Jhjh%2Bn1bGnFU%2FOyd%2BJD3fz%2FlaWm8a3TppVgynz9V%2B2tqXEuqcmQAKQjjMQ9lHYdvigbk9lFRnhh%2BWA3MXzgKmcSRsyZt5YE2tp%2FgH6Z66BZw%3D%3D&Expires=1741787449 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 14:41:20,523 - hoppe_etl_pipeline - INFO - Cleanup of data older than 2024-12-12 completed
2025-03-12 14:41:20,525 - hoppe_etl_pipeline - INFO - Cleanup of data older than 2024-12-12 completed
2025-03-12 14:41:20,527 - hoppe_etl_pipeline - INFO - Cleanup of data older than 2024-12-12 completed
2025-03-12 14:41:20,528 - hoppe_etl_pipeline - INFO - Pipeline run completed successfully in 0:00:51.363418
2025-03-12 14:41:20,529 - hoppe_etl_pipeline - INFO - Pipeline completed in 0:00:51.364419
2025-03-12 14:43:03,924 - hoppe_etl_pipeline - INFO - Starte Verarbeitung um 2025-03-12 14:43:03.924395
2025-03-12 14:43:07,608 - hoppe_etl_pipeline - INFO - Durchsuche Verzeichnis ./data/transformed_data nach Timeseries-Dateien
2025-03-12 14:43:07,612 - hoppe_etl_pipeline - INFO - Gefunden: 6 Timeseries-Dateien aus 1 Tagen
2025-03-12 14:43:07,613 - hoppe_etl_pipeline - INFO - Lade 6 Timeseries-Dateien
2025-03-12 14:43:07,615 - hoppe_etl_pipeline - INFO - Verarbeite Datei 1 von 6
2025-03-12 14:43:07,645 - hoppe_etl_pipeline - INFO - Insgesamt 203157 Zeilen geladen, 203157 vor Deduplizierung
2025-03-12 14:43:07,648 - hoppe_etl_pipeline - INFO - Zeilen nach Entfernen von Nullwerten: 203157
2025-03-12 14:43:07,710 - hoppe_etl_pipeline - INFO - Zeilen nach Deduplizierung: 203157
2025-03-12 14:43:07,712 - hoppe_etl_pipeline - INFO - Pivotisiere Daten
2025-03-12 14:43:07,723 - hoppe_etl_pipeline - INFO - Gefunden: 182 eindeutige Signale
2025-03-12 14:43:07,830 - hoppe_etl_pipeline - INFO - Pivotisierter DataFrame hat 1680 Zeilen und 185 Spalten
2025-03-12 14:43:17,285 - hoppe_etl_pipeline - INFO - Pivotisierte Daten gespeichert nach ./pivoted_timeseries.parquet
2025-03-12 14:43:17,290 - hoppe_etl_pipeline - INFO - Statistiken der pivotisierten Daten:
2025-03-12 14:43:17,292 - hoppe_etl_pipeline - INFO -   Anzahl der Zeilen: 1680
2025-03-12 14:43:17,295 - hoppe_etl_pipeline - INFO -   Anzahl der Spalten: 185
2025-03-12 14:43:17,299 - hoppe_etl_pipeline - INFO -   Eindeutige IMOs: 6
2025-03-12 14:43:17,342 - hoppe_etl_pipeline - INFO - Verarbeitung abgeschlossen nach 0:00:13.418056, Endzeit: 2025-03-12 14:43:17.342451
2025-03-12 15:53:45,248 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/ShipData.json
2025-03-12 15:53:45,383 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/ShipData.parquet
2025-03-12 15:53:45,388 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/ShipData_main_engines.parquet
2025-03-12 15:53:45,393 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/ShipData_aux_engines.parquet
2025-03-12 15:53:51,810 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9400071.json
2025-03-12 15:53:51,832 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9400071.parquet
2025-03-12 15:53:52,063 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9725512.json
2025-03-12 15:53:52,074 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9725512.parquet
2025-03-12 15:53:52,261 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9725524.json
2025-03-12 15:53:52,269 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9725524.parquet
2025-03-12 15:53:52,384 - hoppe_etl_pipeline - ERROR - API request failed: 404 Client Error: Not Found for url: https://api.hoppe-sts.com/fleet/9778399/signals
2025-03-12 15:53:52,613 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9696826.json
2025-03-12 15:53:52,623 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9696826.parquet
2025-03-12 15:53:52,803 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9693290.json
2025-03-12 15:53:52,811 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9693290.parquet
2025-03-12 15:53:53,008 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9306184.json
2025-03-12 15:53:53,017 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9306184.parquet
2025-03-12 15:53:53,138 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9693331.json
2025-03-12 15:53:53,150 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9693331.parquet
2025-03-12 15:53:53,403 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9306287.json
2025-03-12 15:53:53,411 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9306287.parquet
2025-03-12 15:53:53,865 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9306160.json
2025-03-12 15:53:53,876 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9306160.parquet
2025-03-12 15:53:54,096 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9696838.json
2025-03-12 15:53:54,105 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9696838.parquet
2025-03-12 15:53:54,339 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9693329.json
2025-03-12 15:53:54,348 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9693329.parquet
2025-03-12 15:53:54,577 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9395525.json
2025-03-12 15:53:54,589 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9395525.parquet
2025-03-12 15:53:54,850 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Signals_9726566.json
2025-03-12 15:53:54,860 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Signals_9726566.parquet
2025-03-12 15:53:56,259 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Timeseries_9306184.json
2025-03-12 15:53:56,360 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306184
2025-03-12 15:53:56,368 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Timeseries_9306184.parquet
2025-03-12 15:53:56,589 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/3b716516-444b-4179-915b-2a80275f4fc6.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=1gY9yLgPGVF%2B3X8ZO0cneQjg3j8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791836
2025-03-12 15:53:56,595 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/14/53/Gaps_9306184.parquet
2025-03-12 15:53:57,547 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Timeseries_9306160.json
2025-03-12 15:53:57,630 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306160
2025-03-12 15:53:57,635 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Timeseries_9306160.parquet
2025-03-12 15:53:57,727 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/14/53/Gaps_9306160.parquet
2025-03-12 15:53:58,481 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Timeseries_9696838.json
2025-03-12 15:53:58,539 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9696838
2025-03-12 15:53:58,545 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Timeseries_9696838.parquet
2025-03-12 15:53:58,599 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/14/53/Gaps_9696838.parquet
2025-03-12 15:53:58,659 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/3b716516-444b-4179-915b-2a80275f4fc6.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=1gY9yLgPGVF%2B3X8ZO0cneQjg3j8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791836
2025-03-12 15:54:02,720 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/3b716516-444b-4179-915b-2a80275f4fc6.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=1gY9yLgPGVF%2B3X8ZO0cneQjg3j8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791836
2025-03-12 15:54:02,882 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Timeseries_9696826.json
2025-03-12 15:54:02,992 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9696826
2025-03-12 15:54:02,998 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Timeseries_9696826.parquet
2025-03-12 15:54:03,300 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/14/53/Gaps_9696826.parquet
2025-03-12 15:54:04,269 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/14/53/Timeseries_9306287.json
2025-03-12 15:54:04,342 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/eedd7d40-3fe5-4ac4-a31a-f3e6160333af.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=cQ8V8dhEB%2B5PlUe2%2FA9VYVjPyPA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791844
2025-03-12 15:54:04,364 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306287
2025-03-12 15:54:04,370 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/14/53/Timeseries_9306287.parquet
2025-03-12 15:54:04,552 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/14/53/Gaps_9306287.parquet
2025-03-12 15:54:05,070 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/7a2de619-7b3d-4e36-bf34-7bcc5f83da46.json?AWSAccessKeyId=ASIAU3FAITLP7IV6MM3N&Signature=dbNRLFgv96mHwwKK38IyqNvS9qg%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIB6m0I2YcMN64%2B9GP0tVqXFXzfbgU3A9U2YlimRJqYLZAiEAtP8S3TTIbxDZiwjVsImZ3TIW6xMx%2F1U%2B90oXBjwtGdgqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDDceqvtUwt50D%2FM2irjAnW6ZNhjhIY8QJ7GIRhTrmrTsanAK4GsXlLbULRnbg2pe8BQMANQEUBwZfZy%2B6XuWSIaTrTG3E4EvPo9kH7S1agvZGvR5hcX0C1UTwG%2FvJRxgyObfryYCqzfsmxHSqKae646FmPK805T%2FXxTm7akcO4Rj5SNH%2BPEXF2bWANT0rKI7GYZteiiGO%2BscyoQSoaVag1PrfGiHCobtUIaoMDXcThRqYvBcnkGPpGHc%2BAjEm4ayecptrEH4hcj5rz0LVa3pXa23wkrCY8ZE%2BiwEKthjClPdf%2BHX11KZknFkiGLu9B7mLO7T2ZlMlPKy63sbDdDvTMurQm07m2ni61pxL9M13xv%2FD0dm38GGtHtxUzqh4RDw2tAiq%2BZJ9S7XfYkQb%2FtT7AjwNysn8qG2tgS78FtGGQPVEJJx29Y2gvAtfjIoebYqazNedbrq6oE3mzaBBr%2BdSZ9HKqH30vz65tAB%2BHsAF4c5Vgwg8DGvgY6ngH0NmYjW1DTsVVIN42NNmZA8ekVE%2FpNEb6knAmcd0Hbwb%2BAfAi3KmMM2GxJ0Ys4cd%2FPizmNhUKInD5A%2Fj6lBkWyNal8qCj7Bls%2B6XcO1Wvg6VplyabjJapooH2e1L3UbQQngqTrqMAnAkwOgBBfutX2QzI7B3GAKHoRMwpjArUMP1LNC9eddsGVVMnCErczIK1Ew9QOkpxbSFPpgE443A%3D%3D&Expires=1741791844
2025-03-12 15:54:05,492 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/4765d652-bfa7-4e74-aa26-6ad0a077cc3d.json?AWSAccessKeyId=ASIAU3FAITLP3UVQXMWK&Signature=Ks%2F%2BPfY0R2gOX05LFUHzObOAcbI%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDdLPkzTjrNnFMvEd0mfzdgr6mkBMObUSVifodlDfqO0wIgBURvqlZAP6mZh3jFTivagMsu%2Bh3HrMmnOkwox504dyIqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDO2rP7lejczoUOqyOCrjAuRLdfQYEQCbypRQLk5AWauwdEJrBYjCPXX%2BBtxjpyyNsnddWrBdHKeMD9bdcDNdZf4XSFrX6%2BPh%2BgnnW%2BN1j8x7FHK8gFEnpPRkQeeKFCYdtzIMDmcL9nKAZ5sGQRKgntWQbtp2TMD9Jp8oOTbuw%2Be6a9smEoOYKB6Z8KBKZEynm0KixbRdr5qqsySTmTePkXXxhItI%2FpIlB2IakIGiB4iTuMsfsbUar1DCgxa0NQt%2B95%2BvoMYOL5K7FQr2hSsyGJ1UiPcq0sLJKQduBhkxy9nVmCg1JXw16J7ttQSn5vR6uULN32L3cJEtdp1bw9Z5a96fkwGNQbwwfm7sw7HBPFs7KazMPSYgrXfsfLdw2dAvjR1Ttb%2FCkU1tqFKRYOeY77qKmI1Dk1Kb6HBtNkgf0JtRsHypRfUjubkB%2BYVw4jdFhzBwZ6cSRJd%2FLfC2tAZ2Lf9xHbibbqtinAAyG%2FeCMuFrgn0wg8DGvgY6ngHf%2FXMRiH5inuRKMZ6r1nbL8LmLwouE6Bueqp%2FKA%2Flp0JNy81Zut0dh%2BTPcoXjublBJDbgjL7ipW4Pxoa%2BJks4BMuQhSbCzSnhBP6379VmeCC9feCnQPT%2BmdFP6NTazyCzGSSAQ4tFIJzpSlzyJw6KQLfVAFoxi%2BFZICOQhuHSX4Wt9vrjEtlS22SPgdxngsqwYJaQgpmBwmKEoFngnWg%3D%3D&Expires=1741791845
2025-03-12 15:54:06,507 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/eedd7d40-3fe5-4ac4-a31a-f3e6160333af.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=cQ8V8dhEB%2B5PlUe2%2FA9VYVjPyPA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791844
2025-03-12 15:54:07,209 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/7a2de619-7b3d-4e36-bf34-7bcc5f83da46.json?AWSAccessKeyId=ASIAU3FAITLP7IV6MM3N&Signature=dbNRLFgv96mHwwKK38IyqNvS9qg%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIB6m0I2YcMN64%2B9GP0tVqXFXzfbgU3A9U2YlimRJqYLZAiEAtP8S3TTIbxDZiwjVsImZ3TIW6xMx%2F1U%2B90oXBjwtGdgqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDDceqvtUwt50D%2FM2irjAnW6ZNhjhIY8QJ7GIRhTrmrTsanAK4GsXlLbULRnbg2pe8BQMANQEUBwZfZy%2B6XuWSIaTrTG3E4EvPo9kH7S1agvZGvR5hcX0C1UTwG%2FvJRxgyObfryYCqzfsmxHSqKae646FmPK805T%2FXxTm7akcO4Rj5SNH%2BPEXF2bWANT0rKI7GYZteiiGO%2BscyoQSoaVag1PrfGiHCobtUIaoMDXcThRqYvBcnkGPpGHc%2BAjEm4ayecptrEH4hcj5rz0LVa3pXa23wkrCY8ZE%2BiwEKthjClPdf%2BHX11KZknFkiGLu9B7mLO7T2ZlMlPKy63sbDdDvTMurQm07m2ni61pxL9M13xv%2FD0dm38GGtHtxUzqh4RDw2tAiq%2BZJ9S7XfYkQb%2FtT7AjwNysn8qG2tgS78FtGGQPVEJJx29Y2gvAtfjIoebYqazNedbrq6oE3mzaBBr%2BdSZ9HKqH30vz65tAB%2BHsAF4c5Vgwg8DGvgY6ngH0NmYjW1DTsVVIN42NNmZA8ekVE%2FpNEb6knAmcd0Hbwb%2BAfAi3KmMM2GxJ0Ys4cd%2FPizmNhUKInD5A%2Fj6lBkWyNal8qCj7Bls%2B6XcO1Wvg6VplyabjJapooH2e1L3UbQQngqTrqMAnAkwOgBBfutX2QzI7B3GAKHoRMwpjArUMP1LNC9eddsGVVMnCErczIK1Ew9QOkpxbSFPpgE443A%3D%3D&Expires=1741791844
2025-03-12 15:54:07,554 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/4765d652-bfa7-4e74-aa26-6ad0a077cc3d.json?AWSAccessKeyId=ASIAU3FAITLP3UVQXMWK&Signature=Ks%2F%2BPfY0R2gOX05LFUHzObOAcbI%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDdLPkzTjrNnFMvEd0mfzdgr6mkBMObUSVifodlDfqO0wIgBURvqlZAP6mZh3jFTivagMsu%2Bh3HrMmnOkwox504dyIqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDO2rP7lejczoUOqyOCrjAuRLdfQYEQCbypRQLk5AWauwdEJrBYjCPXX%2BBtxjpyyNsnddWrBdHKeMD9bdcDNdZf4XSFrX6%2BPh%2BgnnW%2BN1j8x7FHK8gFEnpPRkQeeKFCYdtzIMDmcL9nKAZ5sGQRKgntWQbtp2TMD9Jp8oOTbuw%2Be6a9smEoOYKB6Z8KBKZEynm0KixbRdr5qqsySTmTePkXXxhItI%2FpIlB2IakIGiB4iTuMsfsbUar1DCgxa0NQt%2B95%2BvoMYOL5K7FQr2hSsyGJ1UiPcq0sLJKQduBhkxy9nVmCg1JXw16J7ttQSn5vR6uULN32L3cJEtdp1bw9Z5a96fkwGNQbwwfm7sw7HBPFs7KazMPSYgrXfsfLdw2dAvjR1Ttb%2FCkU1tqFKRYOeY77qKmI1Dk1Kb6HBtNkgf0JtRsHypRfUjubkB%2BYVw4jdFhzBwZ6cSRJd%2FLfC2tAZ2Lf9xHbibbqtinAAyG%2FeCMuFrgn0wg8DGvgY6ngHf%2FXMRiH5inuRKMZ6r1nbL8LmLwouE6Bueqp%2FKA%2Flp0JNy81Zut0dh%2BTPcoXjublBJDbgjL7ipW4Pxoa%2BJks4BMuQhSbCzSnhBP6379VmeCC9feCnQPT%2BmdFP6NTazyCzGSSAQ4tFIJzpSlzyJw6KQLfVAFoxi%2BFZICOQhuHSX4Wt9vrjEtlS22SPgdxngsqwYJaQgpmBwmKEoFngnWg%3D%3D&Expires=1741791845
2025-03-12 15:54:10,566 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/eedd7d40-3fe5-4ac4-a31a-f3e6160333af.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=cQ8V8dhEB%2B5PlUe2%2FA9VYVjPyPA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791844
2025-03-12 15:54:10,908 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/3b716516-444b-4179-915b-2a80275f4fc6.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=1gY9yLgPGVF%2B3X8ZO0cneQjg3j8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791836
2025-03-12 15:54:11,273 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/7a2de619-7b3d-4e36-bf34-7bcc5f83da46.json?AWSAccessKeyId=ASIAU3FAITLP7IV6MM3N&Signature=dbNRLFgv96mHwwKK38IyqNvS9qg%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIB6m0I2YcMN64%2B9GP0tVqXFXzfbgU3A9U2YlimRJqYLZAiEAtP8S3TTIbxDZiwjVsImZ3TIW6xMx%2F1U%2B90oXBjwtGdgqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDDceqvtUwt50D%2FM2irjAnW6ZNhjhIY8QJ7GIRhTrmrTsanAK4GsXlLbULRnbg2pe8BQMANQEUBwZfZy%2B6XuWSIaTrTG3E4EvPo9kH7S1agvZGvR5hcX0C1UTwG%2FvJRxgyObfryYCqzfsmxHSqKae646FmPK805T%2FXxTm7akcO4Rj5SNH%2BPEXF2bWANT0rKI7GYZteiiGO%2BscyoQSoaVag1PrfGiHCobtUIaoMDXcThRqYvBcnkGPpGHc%2BAjEm4ayecptrEH4hcj5rz0LVa3pXa23wkrCY8ZE%2BiwEKthjClPdf%2BHX11KZknFkiGLu9B7mLO7T2ZlMlPKy63sbDdDvTMurQm07m2ni61pxL9M13xv%2FD0dm38GGtHtxUzqh4RDw2tAiq%2BZJ9S7XfYkQb%2FtT7AjwNysn8qG2tgS78FtGGQPVEJJx29Y2gvAtfjIoebYqazNedbrq6oE3mzaBBr%2BdSZ9HKqH30vz65tAB%2BHsAF4c5Vgwg8DGvgY6ngH0NmYjW1DTsVVIN42NNmZA8ekVE%2FpNEb6knAmcd0Hbwb%2BAfAi3KmMM2GxJ0Ys4cd%2FPizmNhUKInD5A%2Fj6lBkWyNal8qCj7Bls%2B6XcO1Wvg6VplyabjJapooH2e1L3UbQQngqTrqMAnAkwOgBBfutX2QzI7B3GAKHoRMwpjArUMP1LNC9eddsGVVMnCErczIK1Ew9QOkpxbSFPpgE443A%3D%3D&Expires=1741791844
2025-03-12 15:54:11,612 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/4765d652-bfa7-4e74-aa26-6ad0a077cc3d.json?AWSAccessKeyId=ASIAU3FAITLP3UVQXMWK&Signature=Ks%2F%2BPfY0R2gOX05LFUHzObOAcbI%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDdLPkzTjrNnFMvEd0mfzdgr6mkBMObUSVifodlDfqO0wIgBURvqlZAP6mZh3jFTivagMsu%2Bh3HrMmnOkwox504dyIqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDO2rP7lejczoUOqyOCrjAuRLdfQYEQCbypRQLk5AWauwdEJrBYjCPXX%2BBtxjpyyNsnddWrBdHKeMD9bdcDNdZf4XSFrX6%2BPh%2BgnnW%2BN1j8x7FHK8gFEnpPRkQeeKFCYdtzIMDmcL9nKAZ5sGQRKgntWQbtp2TMD9Jp8oOTbuw%2Be6a9smEoOYKB6Z8KBKZEynm0KixbRdr5qqsySTmTePkXXxhItI%2FpIlB2IakIGiB4iTuMsfsbUar1DCgxa0NQt%2B95%2BvoMYOL5K7FQr2hSsyGJ1UiPcq0sLJKQduBhkxy9nVmCg1JXw16J7ttQSn5vR6uULN32L3cJEtdp1bw9Z5a96fkwGNQbwwfm7sw7HBPFs7KazMPSYgrXfsfLdw2dAvjR1Ttb%2FCkU1tqFKRYOeY77qKmI1Dk1Kb6HBtNkgf0JtRsHypRfUjubkB%2BYVw4jdFhzBwZ6cSRJd%2FLfC2tAZ2Lf9xHbibbqtinAAyG%2FeCMuFrgn0wg8DGvgY6ngHf%2FXMRiH5inuRKMZ6r1nbL8LmLwouE6Bueqp%2FKA%2Flp0JNy81Zut0dh%2BTPcoXjublBJDbgjL7ipW4Pxoa%2BJks4BMuQhSbCzSnhBP6379VmeCC9feCnQPT%2BmdFP6NTazyCzGSSAQ4tFIJzpSlzyJw6KQLfVAFoxi%2BFZICOQhuHSX4Wt9vrjEtlS22SPgdxngsqwYJaQgpmBwmKEoFngnWg%3D%3D&Expires=1741791845
2025-03-12 15:54:18,695 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/eedd7d40-3fe5-4ac4-a31a-f3e6160333af.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=cQ8V8dhEB%2B5PlUe2%2FA9VYVjPyPA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791844
2025-03-12 15:54:19,334 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/7a2de619-7b3d-4e36-bf34-7bcc5f83da46.json?AWSAccessKeyId=ASIAU3FAITLP7IV6MM3N&Signature=dbNRLFgv96mHwwKK38IyqNvS9qg%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIB6m0I2YcMN64%2B9GP0tVqXFXzfbgU3A9U2YlimRJqYLZAiEAtP8S3TTIbxDZiwjVsImZ3TIW6xMx%2F1U%2B90oXBjwtGdgqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDDceqvtUwt50D%2FM2irjAnW6ZNhjhIY8QJ7GIRhTrmrTsanAK4GsXlLbULRnbg2pe8BQMANQEUBwZfZy%2B6XuWSIaTrTG3E4EvPo9kH7S1agvZGvR5hcX0C1UTwG%2FvJRxgyObfryYCqzfsmxHSqKae646FmPK805T%2FXxTm7akcO4Rj5SNH%2BPEXF2bWANT0rKI7GYZteiiGO%2BscyoQSoaVag1PrfGiHCobtUIaoMDXcThRqYvBcnkGPpGHc%2BAjEm4ayecptrEH4hcj5rz0LVa3pXa23wkrCY8ZE%2BiwEKthjClPdf%2BHX11KZknFkiGLu9B7mLO7T2ZlMlPKy63sbDdDvTMurQm07m2ni61pxL9M13xv%2FD0dm38GGtHtxUzqh4RDw2tAiq%2BZJ9S7XfYkQb%2FtT7AjwNysn8qG2tgS78FtGGQPVEJJx29Y2gvAtfjIoebYqazNedbrq6oE3mzaBBr%2BdSZ9HKqH30vz65tAB%2BHsAF4c5Vgwg8DGvgY6ngH0NmYjW1DTsVVIN42NNmZA8ekVE%2FpNEb6knAmcd0Hbwb%2BAfAi3KmMM2GxJ0Ys4cd%2FPizmNhUKInD5A%2Fj6lBkWyNal8qCj7Bls%2B6XcO1Wvg6VplyabjJapooH2e1L3UbQQngqTrqMAnAkwOgBBfutX2QzI7B3GAKHoRMwpjArUMP1LNC9eddsGVVMnCErczIK1Ew9QOkpxbSFPpgE443A%3D%3D&Expires=1741791844
2025-03-12 15:54:19,677 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/4765d652-bfa7-4e74-aa26-6ad0a077cc3d.json?AWSAccessKeyId=ASIAU3FAITLP3UVQXMWK&Signature=Ks%2F%2BPfY0R2gOX05LFUHzObOAcbI%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDdLPkzTjrNnFMvEd0mfzdgr6mkBMObUSVifodlDfqO0wIgBURvqlZAP6mZh3jFTivagMsu%2Bh3HrMmnOkwox504dyIqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDO2rP7lejczoUOqyOCrjAuRLdfQYEQCbypRQLk5AWauwdEJrBYjCPXX%2BBtxjpyyNsnddWrBdHKeMD9bdcDNdZf4XSFrX6%2BPh%2BgnnW%2BN1j8x7FHK8gFEnpPRkQeeKFCYdtzIMDmcL9nKAZ5sGQRKgntWQbtp2TMD9Jp8oOTbuw%2Be6a9smEoOYKB6Z8KBKZEynm0KixbRdr5qqsySTmTePkXXxhItI%2FpIlB2IakIGiB4iTuMsfsbUar1DCgxa0NQt%2B95%2BvoMYOL5K7FQr2hSsyGJ1UiPcq0sLJKQduBhkxy9nVmCg1JXw16J7ttQSn5vR6uULN32L3cJEtdp1bw9Z5a96fkwGNQbwwfm7sw7HBPFs7KazMPSYgrXfsfLdw2dAvjR1Ttb%2FCkU1tqFKRYOeY77qKmI1Dk1Kb6HBtNkgf0JtRsHypRfUjubkB%2BYVw4jdFhzBwZ6cSRJd%2FLfC2tAZ2Lf9xHbibbqtinAAyG%2FeCMuFrgn0wg8DGvgY6ngHf%2FXMRiH5inuRKMZ6r1nbL8LmLwouE6Bueqp%2FKA%2Flp0JNy81Zut0dh%2BTPcoXjublBJDbgjL7ipW4Pxoa%2BJks4BMuQhSbCzSnhBP6379VmeCC9feCnQPT%2BmdFP6NTazyCzGSSAQ4tFIJzpSlzyJw6KQLfVAFoxi%2BFZICOQhuHSX4Wt9vrjEtlS22SPgdxngsqwYJaQgpmBwmKEoFngnWg%3D%3D&Expires=1741791845
2025-03-12 15:54:26,966 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/3b716516-444b-4179-915b-2a80275f4fc6.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=1gY9yLgPGVF%2B3X8ZO0cneQjg3j8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791836
2025-03-12 15:54:27,117 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9725524/3b716516-444b-4179-915b-2a80275f4fc6.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=1gY9yLgPGVF%2B3X8ZO0cneQjg3j8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791836 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 15:54:34,839 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/eedd7d40-3fe5-4ac4-a31a-f3e6160333af.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=cQ8V8dhEB%2B5PlUe2%2FA9VYVjPyPA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791844
2025-03-12 15:54:34,980 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9693329/eedd7d40-3fe5-4ac4-a31a-f3e6160333af.json?AWSAccessKeyId=ASIAU3FAITLPTC7KRODC&Signature=cQ8V8dhEB%2B5PlUe2%2FA9VYVjPyPA%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQDm%2BVPKBJgI8DZjjSYisprS7XOOWrtX5RNgFdvQbBgvdwIgdl9rGTOovqlTvWiv8fgrD0u15rAKTTPIuQTj1uPhDOYqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDFR2SbbtSY8KNyCfSrjAsZY3%2FxeHatvPF7nWtkqyWNWCIyPvG6Z7z8bGKM7UcKuuL%2Br8j%2Bwz0ykeiXOyq2tDyXRnF1uwLvPD8XK4x9fbWNM0VyNngAWPButttq0Lx9hCKMDx2ixWwpkk74TWoC5%2FhGlidT9Lu5%2FqLcC5Bfy7VtNjfO%2B0TDbv95c317bjQKAsGzG7SF0bs1yWDMDDhcS76VcqhcoWBJTcGIGR93KpLwIWGnwK%2FIzlvY%2BkYojmLiFsCOBw%2Bqhuoi8RPvVfvM19c%2BcqkpG4tboAk7dPdzDVpV8uX2mhbzyLqNtt6iNTuCUb7Qugs%2BQBdWg670o9Kd6PDwXV%2BpqPMPM9Gt5pNBzJqIAJs9UwcrPFCnS3FNbcFdrzms3dfsGbDYmz2hoYowhgmyXnK3uDdqBTvrbjDe44WjE0tLggaC%2FQKlDYjncdxUTr6iETZqY3xtEnuYhEZdzVIw924Ai9CPAIAFRFWtnvE2rZb4w3KTGvgY6ngF1NYDMkY3HAH52GRB0Vfm%2B20B9XUakFqLMsszCK4x81yX61z0LWCjweVeGBqNbtTZkOam5f01OTHXlPgw8pa5X1h%2FGfPibOyQNMVM9w9b1sl0oCXEBII3pHXP33i44e3Z6VY7g18Zj%2BVa8bvAzSBfRQS7anqILRhffVnFUqcbM6WxB3QEEKe%2FbNi251Ib7Ff%2FdmkpTUrRC2JDHxwro8A%3D%3D&Expires=1741791844 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 15:54:35,472 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/7a2de619-7b3d-4e36-bf34-7bcc5f83da46.json?AWSAccessKeyId=ASIAU3FAITLP7IV6MM3N&Signature=dbNRLFgv96mHwwKK38IyqNvS9qg%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIB6m0I2YcMN64%2B9GP0tVqXFXzfbgU3A9U2YlimRJqYLZAiEAtP8S3TTIbxDZiwjVsImZ3TIW6xMx%2F1U%2B90oXBjwtGdgqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDDceqvtUwt50D%2FM2irjAnW6ZNhjhIY8QJ7GIRhTrmrTsanAK4GsXlLbULRnbg2pe8BQMANQEUBwZfZy%2B6XuWSIaTrTG3E4EvPo9kH7S1agvZGvR5hcX0C1UTwG%2FvJRxgyObfryYCqzfsmxHSqKae646FmPK805T%2FXxTm7akcO4Rj5SNH%2BPEXF2bWANT0rKI7GYZteiiGO%2BscyoQSoaVag1PrfGiHCobtUIaoMDXcThRqYvBcnkGPpGHc%2BAjEm4ayecptrEH4hcj5rz0LVa3pXa23wkrCY8ZE%2BiwEKthjClPdf%2BHX11KZknFkiGLu9B7mLO7T2ZlMlPKy63sbDdDvTMurQm07m2ni61pxL9M13xv%2FD0dm38GGtHtxUzqh4RDw2tAiq%2BZJ9S7XfYkQb%2FtT7AjwNysn8qG2tgS78FtGGQPVEJJx29Y2gvAtfjIoebYqazNedbrq6oE3mzaBBr%2BdSZ9HKqH30vz65tAB%2BHsAF4c5Vgwg8DGvgY6ngH0NmYjW1DTsVVIN42NNmZA8ekVE%2FpNEb6knAmcd0Hbwb%2BAfAi3KmMM2GxJ0Ys4cd%2FPizmNhUKInD5A%2Fj6lBkWyNal8qCj7Bls%2B6XcO1Wvg6VplyabjJapooH2e1L3UbQQngqTrqMAnAkwOgBBfutX2QzI7B3GAKHoRMwpjArUMP1LNC9eddsGVVMnCErczIK1Ew9QOkpxbSFPpgE443A%3D%3D&Expires=1741791844
2025-03-12 15:54:35,593 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9693290/7a2de619-7b3d-4e36-bf34-7bcc5f83da46.json?AWSAccessKeyId=ASIAU3FAITLP7IV6MM3N&Signature=dbNRLFgv96mHwwKK38IyqNvS9qg%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIB6m0I2YcMN64%2B9GP0tVqXFXzfbgU3A9U2YlimRJqYLZAiEAtP8S3TTIbxDZiwjVsImZ3TIW6xMx%2F1U%2B90oXBjwtGdgqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDDDceqvtUwt50D%2FM2irjAnW6ZNhjhIY8QJ7GIRhTrmrTsanAK4GsXlLbULRnbg2pe8BQMANQEUBwZfZy%2B6XuWSIaTrTG3E4EvPo9kH7S1agvZGvR5hcX0C1UTwG%2FvJRxgyObfryYCqzfsmxHSqKae646FmPK805T%2FXxTm7akcO4Rj5SNH%2BPEXF2bWANT0rKI7GYZteiiGO%2BscyoQSoaVag1PrfGiHCobtUIaoMDXcThRqYvBcnkGPpGHc%2BAjEm4ayecptrEH4hcj5rz0LVa3pXa23wkrCY8ZE%2BiwEKthjClPdf%2BHX11KZknFkiGLu9B7mLO7T2ZlMlPKy63sbDdDvTMurQm07m2ni61pxL9M13xv%2FD0dm38GGtHtxUzqh4RDw2tAiq%2BZJ9S7XfYkQb%2FtT7AjwNysn8qG2tgS78FtGGQPVEJJx29Y2gvAtfjIoebYqazNedbrq6oE3mzaBBr%2BdSZ9HKqH30vz65tAB%2BHsAF4c5Vgwg8DGvgY6ngH0NmYjW1DTsVVIN42NNmZA8ekVE%2FpNEb6knAmcd0Hbwb%2BAfAi3KmMM2GxJ0Ys4cd%2FPizmNhUKInD5A%2Fj6lBkWyNal8qCj7Bls%2B6XcO1Wvg6VplyabjJapooH2e1L3UbQQngqTrqMAnAkwOgBBfutX2QzI7B3GAKHoRMwpjArUMP1LNC9eddsGVVMnCErczIK1Ew9QOkpxbSFPpgE443A%3D%3D&Expires=1741791844 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 15:54:35,800 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/4765d652-bfa7-4e74-aa26-6ad0a077cc3d.json?AWSAccessKeyId=ASIAU3FAITLP3UVQXMWK&Signature=Ks%2F%2BPfY0R2gOX05LFUHzObOAcbI%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDdLPkzTjrNnFMvEd0mfzdgr6mkBMObUSVifodlDfqO0wIgBURvqlZAP6mZh3jFTivagMsu%2Bh3HrMmnOkwox504dyIqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDO2rP7lejczoUOqyOCrjAuRLdfQYEQCbypRQLk5AWauwdEJrBYjCPXX%2BBtxjpyyNsnddWrBdHKeMD9bdcDNdZf4XSFrX6%2BPh%2BgnnW%2BN1j8x7FHK8gFEnpPRkQeeKFCYdtzIMDmcL9nKAZ5sGQRKgntWQbtp2TMD9Jp8oOTbuw%2Be6a9smEoOYKB6Z8KBKZEynm0KixbRdr5qqsySTmTePkXXxhItI%2FpIlB2IakIGiB4iTuMsfsbUar1DCgxa0NQt%2B95%2BvoMYOL5K7FQr2hSsyGJ1UiPcq0sLJKQduBhkxy9nVmCg1JXw16J7ttQSn5vR6uULN32L3cJEtdp1bw9Z5a96fkwGNQbwwfm7sw7HBPFs7KazMPSYgrXfsfLdw2dAvjR1Ttb%2FCkU1tqFKRYOeY77qKmI1Dk1Kb6HBtNkgf0JtRsHypRfUjubkB%2BYVw4jdFhzBwZ6cSRJd%2FLfC2tAZ2Lf9xHbibbqtinAAyG%2FeCMuFrgn0wg8DGvgY6ngHf%2FXMRiH5inuRKMZ6r1nbL8LmLwouE6Bueqp%2FKA%2Flp0JNy81Zut0dh%2BTPcoXjublBJDbgjL7ipW4Pxoa%2BJks4BMuQhSbCzSnhBP6379VmeCC9feCnQPT%2BmdFP6NTazyCzGSSAQ4tFIJzpSlzyJw6KQLfVAFoxi%2BFZICOQhuHSX4Wt9vrjEtlS22SPgdxngsqwYJaQgpmBwmKEoFngnWg%3D%3D&Expires=1741791845
2025-03-12 15:54:35,930 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9726566/4765d652-bfa7-4e74-aa26-6ad0a077cc3d.json?AWSAccessKeyId=ASIAU3FAITLP3UVQXMWK&Signature=Ks%2F%2BPfY0R2gOX05LFUHzObOAcbI%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDdLPkzTjrNnFMvEd0mfzdgr6mkBMObUSVifodlDfqO0wIgBURvqlZAP6mZh3jFTivagMsu%2Bh3HrMmnOkwox504dyIqjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDO2rP7lejczoUOqyOCrjAuRLdfQYEQCbypRQLk5AWauwdEJrBYjCPXX%2BBtxjpyyNsnddWrBdHKeMD9bdcDNdZf4XSFrX6%2BPh%2BgnnW%2BN1j8x7FHK8gFEnpPRkQeeKFCYdtzIMDmcL9nKAZ5sGQRKgntWQbtp2TMD9Jp8oOTbuw%2Be6a9smEoOYKB6Z8KBKZEynm0KixbRdr5qqsySTmTePkXXxhItI%2FpIlB2IakIGiB4iTuMsfsbUar1DCgxa0NQt%2B95%2BvoMYOL5K7FQr2hSsyGJ1UiPcq0sLJKQduBhkxy9nVmCg1JXw16J7ttQSn5vR6uULN32L3cJEtdp1bw9Z5a96fkwGNQbwwfm7sw7HBPFs7KazMPSYgrXfsfLdw2dAvjR1Ttb%2FCkU1tqFKRYOeY77qKmI1Dk1Kb6HBtNkgf0JtRsHypRfUjubkB%2BYVw4jdFhzBwZ6cSRJd%2FLfC2tAZ2Lf9xHbibbqtinAAyG%2FeCMuFrgn0wg8DGvgY6ngHf%2FXMRiH5inuRKMZ6r1nbL8LmLwouE6Bueqp%2FKA%2Flp0JNy81Zut0dh%2BTPcoXjublBJDbgjL7ipW4Pxoa%2BJks4BMuQhSbCzSnhBP6379VmeCC9feCnQPT%2BmdFP6NTazyCzGSSAQ4tFIJzpSlzyJw6KQLfVAFoxi%2BFZICOQhuHSX4Wt9vrjEtlS22SPgdxngsqwYJaQgpmBwmKEoFngnWg%3D%3D&Expires=1741791845 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 16:02:48,299 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/ShipData.json
2025-03-12 16:02:48,309 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/ShipData.parquet
2025-03-12 16:02:48,311 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/ShipData_main_engines.parquet
2025-03-12 16:02:48,314 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/ShipData_aux_engines.parquet
2025-03-12 16:02:55,077 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9400071.json
2025-03-12 16:02:55,085 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9400071.parquet
2025-03-12 16:02:55,314 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9725512.json
2025-03-12 16:02:55,322 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9725512.parquet
2025-03-12 16:02:55,509 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9725524.json
2025-03-12 16:02:55,516 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9725524.parquet
2025-03-12 16:02:55,627 - hoppe_etl_pipeline - ERROR - API request failed: 404 Client Error: Not Found for url: https://api.hoppe-sts.com/fleet/9778399/signals
2025-03-12 16:02:55,864 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9696826.json
2025-03-12 16:02:55,874 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9696826.parquet
2025-03-12 16:02:56,075 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9693290.json
2025-03-12 16:02:56,081 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9693290.parquet
2025-03-12 16:02:56,322 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9306184.json
2025-03-12 16:02:56,330 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9306184.parquet
2025-03-12 16:02:56,458 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9693331.json
2025-03-12 16:02:56,466 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9693331.parquet
2025-03-12 16:02:56,740 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9306287.json
2025-03-12 16:02:56,748 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9306287.parquet
2025-03-12 16:02:57,025 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9306160.json
2025-03-12 16:02:57,034 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9306160.parquet
2025-03-12 16:02:57,333 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9696838.json
2025-03-12 16:02:57,341 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9696838.parquet
2025-03-12 16:02:57,606 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9693329.json
2025-03-12 16:02:57,614 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9693329.parquet
2025-03-12 16:02:57,859 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9395525.json
2025-03-12 16:02:57,869 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9395525.parquet
2025-03-12 16:02:58,129 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Signals_9726566.json
2025-03-12 16:02:58,139 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Signals_9726566.parquet
2025-03-12 16:02:58,939 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Timeseries_9725512.json
2025-03-12 16:02:59,071 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9725512
2025-03-12 16:02:59,078 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Timeseries_9725512.parquet
2025-03-12 16:02:59,323 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/15/02/Gaps_9725512.parquet
2025-03-12 16:02:59,632 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Timeseries_9696826.json
2025-03-12 16:02:59,778 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9696826
2025-03-12 16:02:59,783 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Timeseries_9696826.parquet
2025-03-12 16:02:59,878 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/7f4742b5-8596-4339-b2ac-276f52b49cc9.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=3upKwKztThDZMa0SKABAVO%2FKiG4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792379
2025-03-12 16:03:00,123 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/15/02/Gaps_9696826.parquet
2025-03-12 16:03:00,317 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Timeseries_9306184.json
2025-03-12 16:03:00,437 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306184
2025-03-12 16:03:00,444 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Timeseries_9306184.parquet
2025-03-12 16:03:00,529 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/15/02/Gaps_9306184.parquet
2025-03-12 16:03:00,966 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/4d54d9b3-659a-4fb8-8da4-52e2694911c9.json?AWSAccessKeyId=ASIAU3FAITLPQTFM4UXS&Signature=p8eiIdHZIGCddhagUlwjC8gk7ss%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDhZS2Z03qAfXsDbllo1Quq449r0GK8xH2jDPRwLsA%2FJwIgY1iWFNMj%2BlBii2a8lV8Du0D0Mb%2FpnfKEXVLQksEUrq8qjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDGQaEpIBbqRHeVisZSrjAn6fOnbRqsSAF9KXaiaU6nJIkfn3%2Fs9w5YxGgTKygWh4Kbdso9y2Yc4y24oONkqLoKuYGJ6n2EmiCiGWM1JeF2fLnJQz4kq5XQvEe%2BFZzXPBrTndsRp8%2BkK0b5xiPM6O6IVsvOmJZi1u4VSgwblTFcS4NbgaJfAjeap3talPLTDQaXmL5mNEQcEpwr93vKAY2FDQTlJ2iu8qRDnjP2RU%2Bugs3Gab%2FBa0OjlGFxspMgfgg15jw5SqxB71rQH0MsiIjLjKDrDJy8woj706S6ep2qiTkVXVe2yJOb4EYjl%2BPAwFmE9B%2F7dT0ynxFIERvQvM25ThGQs7u%2BqBOfu7135I2OM2M3n01jLIInEfQzItigfcQ1QFOkRvFh6fjOYfSumRUMajIK0eCZM%2FGyBgtiWhmvxDSSgYogWsxGQ2jb9kRh31T%2BoXmTNOuQ2O4LaibTjass%2B%2FiZTHuxgOdtO8jdN6JM%2B5g64wx8DGvgY6ngEv3FMnVjnuks3KnIwLAM06z3tokSC7r7AS0jfbPj%2BSS0BvJIn62aqkFoBU2ZR8BZXRdxYB3uWA%2Bzf2zkLKKYeCOf6%2FO4qZLi4tlMIahNmL0E4CBQDPXrz9PS%2F7I9iluKNaehbHGPrBFSvSxjGkka7WsxBEpIUcntpkPg0SIPB0taQB5L3T2ct7IocFUosGC6VSLEdYIYpQFPX40TLnEg%3D%3D&Expires=1741792380
2025-03-12 16:03:01,187 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Timeseries_9306287.json
2025-03-12 16:03:01,271 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306287
2025-03-12 16:03:01,290 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Timeseries_9306287.parquet
2025-03-12 16:03:01,473 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/15/02/Gaps_9306287.parquet
2025-03-12 16:03:01,680 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Timeseries_9306160.json
2025-03-12 16:03:01,785 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9306160
2025-03-12 16:03:01,795 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Timeseries_9306160.parquet
2025-03-12 16:03:01,880 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/15/02/Gaps_9306160.parquet
2025-03-12 16:03:02,089 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/7f4742b5-8596-4339-b2ac-276f52b49cc9.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=3upKwKztThDZMa0SKABAVO%2FKiG4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792379
2025-03-12 16:03:02,274 - hoppe_etl_pipeline - INFO - Data saved to ./data/raw_data/2025/03/12/15/02/Timeseries_9696838.json
2025-03-12 16:03:02,339 - hoppe_etl_pipeline - INFO - No historical timeseries data found for ship 9696838
2025-03-12 16:03:02,345 - hoppe_etl_pipeline - INFO - Data saved to ./data/transformed_data/2025/03/12/15/02/Timeseries_9696838.parquet
2025-03-12 16:03:02,400 - hoppe_etl_pipeline - INFO - Data saved to ./data/gaps_data/2025/03/12/15/02/Gaps_9696838.parquet
2025-03-12 16:03:03,106 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/4d54d9b3-659a-4fb8-8da4-52e2694911c9.json?AWSAccessKeyId=ASIAU3FAITLPQTFM4UXS&Signature=p8eiIdHZIGCddhagUlwjC8gk7ss%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDhZS2Z03qAfXsDbllo1Quq449r0GK8xH2jDPRwLsA%2FJwIgY1iWFNMj%2BlBii2a8lV8Du0D0Mb%2FpnfKEXVLQksEUrq8qjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDGQaEpIBbqRHeVisZSrjAn6fOnbRqsSAF9KXaiaU6nJIkfn3%2Fs9w5YxGgTKygWh4Kbdso9y2Yc4y24oONkqLoKuYGJ6n2EmiCiGWM1JeF2fLnJQz4kq5XQvEe%2BFZzXPBrTndsRp8%2BkK0b5xiPM6O6IVsvOmJZi1u4VSgwblTFcS4NbgaJfAjeap3talPLTDQaXmL5mNEQcEpwr93vKAY2FDQTlJ2iu8qRDnjP2RU%2Bugs3Gab%2FBa0OjlGFxspMgfgg15jw5SqxB71rQH0MsiIjLjKDrDJy8woj706S6ep2qiTkVXVe2yJOb4EYjl%2BPAwFmE9B%2F7dT0ynxFIERvQvM25ThGQs7u%2BqBOfu7135I2OM2M3n01jLIInEfQzItigfcQ1QFOkRvFh6fjOYfSumRUMajIK0eCZM%2FGyBgtiWhmvxDSSgYogWsxGQ2jb9kRh31T%2BoXmTNOuQ2O4LaibTjass%2B%2FiZTHuxgOdtO8jdN6JM%2B5g64wx8DGvgY6ngEv3FMnVjnuks3KnIwLAM06z3tokSC7r7AS0jfbPj%2BSS0BvJIn62aqkFoBU2ZR8BZXRdxYB3uWA%2Bzf2zkLKKYeCOf6%2FO4qZLi4tlMIahNmL0E4CBQDPXrz9PS%2F7I9iluKNaehbHGPrBFSvSxjGkka7WsxBEpIUcntpkPg0SIPB0taQB5L3T2ct7IocFUosGC6VSLEdYIYpQFPX40TLnEg%3D%3D&Expires=1741792380
2025-03-12 16:03:04,588 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/d918352f-acfc-4d19-93b5-aa8602e50a11.json?AWSAccessKeyId=ASIAU3FAITLPWB7NJBZM&Signature=RYqVdvBp54IiTPu6W4b0%2BYh86c8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQCf0MIO6MLEjr21yK3YmkmHEyLKs0fLs55QzpkhopTYJAIgMdWcXo4V8pzFvC1Olu7BSoHTC2fChMiM5cx%2BfXhK9MUqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDCAuSmxhzkRiDUmsMirjAoD53jDUb5BrZ4biUXs55JlVUdq65nNQY7VQ99wbGt3Ph9%2Bux2GFWniZhUHKM92mTrtG0VApFeZ5t1ME596oFjsgUfJex81AvUdHX0EalU%2BbSXInPXex3Me4dLAXOuFWMpaSgbHUNyIL8q%2BAZDl55Nrgp%2FLxSh1arScVuApF%2BaUU18WalaJ2Mv60LC4RlBe7YL1FFmgKvO5JFJ0vZqb0kTkpjIodWG3znIg5W77gJYYgyhgMKvg8oGkjKBCTamPjLQG9werzRQPYl5ITNCh55hVlm8qnHo4GaFFntE52wGSL8mzpQUTPRIdBEhE%2F%2BGD64VFuQXNax3JCgW72Kd0%2FUbhUydQ6U1N%2Ba8%2BHcEqVjrkzrTA9UgT3kKzgMPBqxLWwsIkzfdUu%2FvpixggeD%2FS81%2BPvFO%2F3hQFX%2BMa56whuvmhA9M1ERDznULRic5FWlKIx0ZVsDlAc%2FClFCZLMsRFuFtumE9Iwh6zGvgY6ngFg52W605AFmCUtdxwGIlueNMP4jWOExZjSh2pkrOqhrmJ8SW2dPSVPuzWBItiRpMbaWpehr1hN8qnKMjk6TOwbelXcbfyZkJERPMYBOjkDyBjLzwEoF8Rah9n%2BPwDLcKQtNX4BWdOZlv9E%2F2FlJEGPjQMREr0LU53xqgc%2Boquy2YRDjCfSjcOdeCCYcfqBf4qY0fYaZtkY7VGqP%2BBSNw%3D%3D&Expires=1741792384
2025-03-12 16:03:06,221 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/7f4742b5-8596-4339-b2ac-276f52b49cc9.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=3upKwKztThDZMa0SKABAVO%2FKiG4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792379
2025-03-12 16:03:06,647 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/d918352f-acfc-4d19-93b5-aa8602e50a11.json?AWSAccessKeyId=ASIAU3FAITLPWB7NJBZM&Signature=RYqVdvBp54IiTPu6W4b0%2BYh86c8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQCf0MIO6MLEjr21yK3YmkmHEyLKs0fLs55QzpkhopTYJAIgMdWcXo4V8pzFvC1Olu7BSoHTC2fChMiM5cx%2BfXhK9MUqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDCAuSmxhzkRiDUmsMirjAoD53jDUb5BrZ4biUXs55JlVUdq65nNQY7VQ99wbGt3Ph9%2Bux2GFWniZhUHKM92mTrtG0VApFeZ5t1ME596oFjsgUfJex81AvUdHX0EalU%2BbSXInPXex3Me4dLAXOuFWMpaSgbHUNyIL8q%2BAZDl55Nrgp%2FLxSh1arScVuApF%2BaUU18WalaJ2Mv60LC4RlBe7YL1FFmgKvO5JFJ0vZqb0kTkpjIodWG3znIg5W77gJYYgyhgMKvg8oGkjKBCTamPjLQG9werzRQPYl5ITNCh55hVlm8qnHo4GaFFntE52wGSL8mzpQUTPRIdBEhE%2F%2BGD64VFuQXNax3JCgW72Kd0%2FUbhUydQ6U1N%2Ba8%2BHcEqVjrkzrTA9UgT3kKzgMPBqxLWwsIkzfdUu%2FvpixggeD%2FS81%2BPvFO%2F3hQFX%2BMa56whuvmhA9M1ERDznULRic5FWlKIx0ZVsDlAc%2FClFCZLMsRFuFtumE9Iwh6zGvgY6ngFg52W605AFmCUtdxwGIlueNMP4jWOExZjSh2pkrOqhrmJ8SW2dPSVPuzWBItiRpMbaWpehr1hN8qnKMjk6TOwbelXcbfyZkJERPMYBOjkDyBjLzwEoF8Rah9n%2BPwDLcKQtNX4BWdOZlv9E%2F2FlJEGPjQMREr0LU53xqgc%2Boquy2YRDjCfSjcOdeCCYcfqBf4qY0fYaZtkY7VGqP%2BBSNw%3D%3D&Expires=1741792384
2025-03-12 16:03:07,225 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/4d54d9b3-659a-4fb8-8da4-52e2694911c9.json?AWSAccessKeyId=ASIAU3FAITLPQTFM4UXS&Signature=p8eiIdHZIGCddhagUlwjC8gk7ss%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDhZS2Z03qAfXsDbllo1Quq449r0GK8xH2jDPRwLsA%2FJwIgY1iWFNMj%2BlBii2a8lV8Du0D0Mb%2FpnfKEXVLQksEUrq8qjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDGQaEpIBbqRHeVisZSrjAn6fOnbRqsSAF9KXaiaU6nJIkfn3%2Fs9w5YxGgTKygWh4Kbdso9y2Yc4y24oONkqLoKuYGJ6n2EmiCiGWM1JeF2fLnJQz4kq5XQvEe%2BFZzXPBrTndsRp8%2BkK0b5xiPM6O6IVsvOmJZi1u4VSgwblTFcS4NbgaJfAjeap3talPLTDQaXmL5mNEQcEpwr93vKAY2FDQTlJ2iu8qRDnjP2RU%2Bugs3Gab%2FBa0OjlGFxspMgfgg15jw5SqxB71rQH0MsiIjLjKDrDJy8woj706S6ep2qiTkVXVe2yJOb4EYjl%2BPAwFmE9B%2F7dT0ynxFIERvQvM25ThGQs7u%2BqBOfu7135I2OM2M3n01jLIInEfQzItigfcQ1QFOkRvFh6fjOYfSumRUMajIK0eCZM%2FGyBgtiWhmvxDSSgYogWsxGQ2jb9kRh31T%2BoXmTNOuQ2O4LaibTjass%2B%2FiZTHuxgOdtO8jdN6JM%2B5g64wx8DGvgY6ngEv3FMnVjnuks3KnIwLAM06z3tokSC7r7AS0jfbPj%2BSS0BvJIn62aqkFoBU2ZR8BZXRdxYB3uWA%2Bzf2zkLKKYeCOf6%2FO4qZLi4tlMIahNmL0E4CBQDPXrz9PS%2F7I9iluKNaehbHGPrBFSvSxjGkka7WsxBEpIUcntpkPg0SIPB0taQB5L3T2ct7IocFUosGC6VSLEdYIYpQFPX40TLnEg%3D%3D&Expires=1741792380
2025-03-12 16:03:07,737 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b7fa1681-b83a-405c-b028-60c8d2789cc4.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=hnVO3b2U5zEeXDxtNwg%2FPXckLqQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792387
2025-03-12 16:03:09,798 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b7fa1681-b83a-405c-b028-60c8d2789cc4.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=hnVO3b2U5zEeXDxtNwg%2FPXckLqQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792387
2025-03-12 16:03:10,710 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/d918352f-acfc-4d19-93b5-aa8602e50a11.json?AWSAccessKeyId=ASIAU3FAITLPWB7NJBZM&Signature=RYqVdvBp54IiTPu6W4b0%2BYh86c8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQCf0MIO6MLEjr21yK3YmkmHEyLKs0fLs55QzpkhopTYJAIgMdWcXo4V8pzFvC1Olu7BSoHTC2fChMiM5cx%2BfXhK9MUqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDCAuSmxhzkRiDUmsMirjAoD53jDUb5BrZ4biUXs55JlVUdq65nNQY7VQ99wbGt3Ph9%2Bux2GFWniZhUHKM92mTrtG0VApFeZ5t1ME596oFjsgUfJex81AvUdHX0EalU%2BbSXInPXex3Me4dLAXOuFWMpaSgbHUNyIL8q%2BAZDl55Nrgp%2FLxSh1arScVuApF%2BaUU18WalaJ2Mv60LC4RlBe7YL1FFmgKvO5JFJ0vZqb0kTkpjIodWG3znIg5W77gJYYgyhgMKvg8oGkjKBCTamPjLQG9werzRQPYl5ITNCh55hVlm8qnHo4GaFFntE52wGSL8mzpQUTPRIdBEhE%2F%2BGD64VFuQXNax3JCgW72Kd0%2FUbhUydQ6U1N%2Ba8%2BHcEqVjrkzrTA9UgT3kKzgMPBqxLWwsIkzfdUu%2FvpixggeD%2FS81%2BPvFO%2F3hQFX%2BMa56whuvmhA9M1ERDznULRic5FWlKIx0ZVsDlAc%2FClFCZLMsRFuFtumE9Iwh6zGvgY6ngFg52W605AFmCUtdxwGIlueNMP4jWOExZjSh2pkrOqhrmJ8SW2dPSVPuzWBItiRpMbaWpehr1hN8qnKMjk6TOwbelXcbfyZkJERPMYBOjkDyBjLzwEoF8Rah9n%2BPwDLcKQtNX4BWdOZlv9E%2F2FlJEGPjQMREr0LU53xqgc%2Boquy2YRDjCfSjcOdeCCYcfqBf4qY0fYaZtkY7VGqP%2BBSNw%3D%3D&Expires=1741792384
2025-03-12 16:03:13,917 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b7fa1681-b83a-405c-b028-60c8d2789cc4.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=hnVO3b2U5zEeXDxtNwg%2FPXckLqQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792387
2025-03-12 16:03:14,347 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/7f4742b5-8596-4339-b2ac-276f52b49cc9.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=3upKwKztThDZMa0SKABAVO%2FKiG4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792379
2025-03-12 16:03:15,287 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/4d54d9b3-659a-4fb8-8da4-52e2694911c9.json?AWSAccessKeyId=ASIAU3FAITLPQTFM4UXS&Signature=p8eiIdHZIGCddhagUlwjC8gk7ss%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDhZS2Z03qAfXsDbllo1Quq449r0GK8xH2jDPRwLsA%2FJwIgY1iWFNMj%2BlBii2a8lV8Du0D0Mb%2FpnfKEXVLQksEUrq8qjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDGQaEpIBbqRHeVisZSrjAn6fOnbRqsSAF9KXaiaU6nJIkfn3%2Fs9w5YxGgTKygWh4Kbdso9y2Yc4y24oONkqLoKuYGJ6n2EmiCiGWM1JeF2fLnJQz4kq5XQvEe%2BFZzXPBrTndsRp8%2BkK0b5xiPM6O6IVsvOmJZi1u4VSgwblTFcS4NbgaJfAjeap3talPLTDQaXmL5mNEQcEpwr93vKAY2FDQTlJ2iu8qRDnjP2RU%2Bugs3Gab%2FBa0OjlGFxspMgfgg15jw5SqxB71rQH0MsiIjLjKDrDJy8woj706S6ep2qiTkVXVe2yJOb4EYjl%2BPAwFmE9B%2F7dT0ynxFIERvQvM25ThGQs7u%2BqBOfu7135I2OM2M3n01jLIInEfQzItigfcQ1QFOkRvFh6fjOYfSumRUMajIK0eCZM%2FGyBgtiWhmvxDSSgYogWsxGQ2jb9kRh31T%2BoXmTNOuQ2O4LaibTjass%2B%2FiZTHuxgOdtO8jdN6JM%2B5g64wx8DGvgY6ngEv3FMnVjnuks3KnIwLAM06z3tokSC7r7AS0jfbPj%2BSS0BvJIn62aqkFoBU2ZR8BZXRdxYB3uWA%2Bzf2zkLKKYeCOf6%2FO4qZLi4tlMIahNmL0E4CBQDPXrz9PS%2F7I9iluKNaehbHGPrBFSvSxjGkka7WsxBEpIUcntpkPg0SIPB0taQB5L3T2ct7IocFUosGC6VSLEdYIYpQFPX40TLnEg%3D%3D&Expires=1741792380
2025-03-12 16:03:18,849 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/d918352f-acfc-4d19-93b5-aa8602e50a11.json?AWSAccessKeyId=ASIAU3FAITLPWB7NJBZM&Signature=RYqVdvBp54IiTPu6W4b0%2BYh86c8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQCf0MIO6MLEjr21yK3YmkmHEyLKs0fLs55QzpkhopTYJAIgMdWcXo4V8pzFvC1Olu7BSoHTC2fChMiM5cx%2BfXhK9MUqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDCAuSmxhzkRiDUmsMirjAoD53jDUb5BrZ4biUXs55JlVUdq65nNQY7VQ99wbGt3Ph9%2Bux2GFWniZhUHKM92mTrtG0VApFeZ5t1ME596oFjsgUfJex81AvUdHX0EalU%2BbSXInPXex3Me4dLAXOuFWMpaSgbHUNyIL8q%2BAZDl55Nrgp%2FLxSh1arScVuApF%2BaUU18WalaJ2Mv60LC4RlBe7YL1FFmgKvO5JFJ0vZqb0kTkpjIodWG3znIg5W77gJYYgyhgMKvg8oGkjKBCTamPjLQG9werzRQPYl5ITNCh55hVlm8qnHo4GaFFntE52wGSL8mzpQUTPRIdBEhE%2F%2BGD64VFuQXNax3JCgW72Kd0%2FUbhUydQ6U1N%2Ba8%2BHcEqVjrkzrTA9UgT3kKzgMPBqxLWwsIkzfdUu%2FvpixggeD%2FS81%2BPvFO%2F3hQFX%2BMa56whuvmhA9M1ERDznULRic5FWlKIx0ZVsDlAc%2FClFCZLMsRFuFtumE9Iwh6zGvgY6ngFg52W605AFmCUtdxwGIlueNMP4jWOExZjSh2pkrOqhrmJ8SW2dPSVPuzWBItiRpMbaWpehr1hN8qnKMjk6TOwbelXcbfyZkJERPMYBOjkDyBjLzwEoF8Rah9n%2BPwDLcKQtNX4BWdOZlv9E%2F2FlJEGPjQMREr0LU53xqgc%2Boquy2YRDjCfSjcOdeCCYcfqBf4qY0fYaZtkY7VGqP%2BBSNw%3D%3D&Expires=1741792384
2025-03-12 16:03:21,992 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b7fa1681-b83a-405c-b028-60c8d2789cc4.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=hnVO3b2U5zEeXDxtNwg%2FPXckLqQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792387
2025-03-12 16:03:30,477 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9725524/7f4742b5-8596-4339-b2ac-276f52b49cc9.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=3upKwKztThDZMa0SKABAVO%2FKiG4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792379
2025-03-12 16:03:30,611 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9725524/7f4742b5-8596-4339-b2ac-276f52b49cc9.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=3upKwKztThDZMa0SKABAVO%2FKiG4%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792379 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 16:03:31,421 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693290/4d54d9b3-659a-4fb8-8da4-52e2694911c9.json?AWSAccessKeyId=ASIAU3FAITLPQTFM4UXS&Signature=p8eiIdHZIGCddhagUlwjC8gk7ss%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDhZS2Z03qAfXsDbllo1Quq449r0GK8xH2jDPRwLsA%2FJwIgY1iWFNMj%2BlBii2a8lV8Du0D0Mb%2FpnfKEXVLQksEUrq8qjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDGQaEpIBbqRHeVisZSrjAn6fOnbRqsSAF9KXaiaU6nJIkfn3%2Fs9w5YxGgTKygWh4Kbdso9y2Yc4y24oONkqLoKuYGJ6n2EmiCiGWM1JeF2fLnJQz4kq5XQvEe%2BFZzXPBrTndsRp8%2BkK0b5xiPM6O6IVsvOmJZi1u4VSgwblTFcS4NbgaJfAjeap3talPLTDQaXmL5mNEQcEpwr93vKAY2FDQTlJ2iu8qRDnjP2RU%2Bugs3Gab%2FBa0OjlGFxspMgfgg15jw5SqxB71rQH0MsiIjLjKDrDJy8woj706S6ep2qiTkVXVe2yJOb4EYjl%2BPAwFmE9B%2F7dT0ynxFIERvQvM25ThGQs7u%2BqBOfu7135I2OM2M3n01jLIInEfQzItigfcQ1QFOkRvFh6fjOYfSumRUMajIK0eCZM%2FGyBgtiWhmvxDSSgYogWsxGQ2jb9kRh31T%2BoXmTNOuQ2O4LaibTjass%2B%2FiZTHuxgOdtO8jdN6JM%2B5g64wx8DGvgY6ngEv3FMnVjnuks3KnIwLAM06z3tokSC7r7AS0jfbPj%2BSS0BvJIn62aqkFoBU2ZR8BZXRdxYB3uWA%2Bzf2zkLKKYeCOf6%2FO4qZLi4tlMIahNmL0E4CBQDPXrz9PS%2F7I9iluKNaehbHGPrBFSvSxjGkka7WsxBEpIUcntpkPg0SIPB0taQB5L3T2ct7IocFUosGC6VSLEdYIYpQFPX40TLnEg%3D%3D&Expires=1741792380
2025-03-12 16:03:31,479 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9693290/4d54d9b3-659a-4fb8-8da4-52e2694911c9.json?AWSAccessKeyId=ASIAU3FAITLPQTFM4UXS&Signature=p8eiIdHZIGCddhagUlwjC8gk7ss%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJHMEUCIQDhZS2Z03qAfXsDbllo1Quq449r0GK8xH2jDPRwLsA%2FJwIgY1iWFNMj%2BlBii2a8lV8Du0D0Mb%2FpnfKEXVLQksEUrq8qjwMIwP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDGQaEpIBbqRHeVisZSrjAn6fOnbRqsSAF9KXaiaU6nJIkfn3%2Fs9w5YxGgTKygWh4Kbdso9y2Yc4y24oONkqLoKuYGJ6n2EmiCiGWM1JeF2fLnJQz4kq5XQvEe%2BFZzXPBrTndsRp8%2BkK0b5xiPM6O6IVsvOmJZi1u4VSgwblTFcS4NbgaJfAjeap3talPLTDQaXmL5mNEQcEpwr93vKAY2FDQTlJ2iu8qRDnjP2RU%2Bugs3Gab%2FBa0OjlGFxspMgfgg15jw5SqxB71rQH0MsiIjLjKDrDJy8woj706S6ep2qiTkVXVe2yJOb4EYjl%2BPAwFmE9B%2F7dT0ynxFIERvQvM25ThGQs7u%2BqBOfu7135I2OM2M3n01jLIInEfQzItigfcQ1QFOkRvFh6fjOYfSumRUMajIK0eCZM%2FGyBgtiWhmvxDSSgYogWsxGQ2jb9kRh31T%2BoXmTNOuQ2O4LaibTjass%2B%2FiZTHuxgOdtO8jdN6JM%2B5g64wx8DGvgY6ngEv3FMnVjnuks3KnIwLAM06z3tokSC7r7AS0jfbPj%2BSS0BvJIn62aqkFoBU2ZR8BZXRdxYB3uWA%2Bzf2zkLKKYeCOf6%2FO4qZLi4tlMIahNmL0E4CBQDPXrz9PS%2F7I9iluKNaehbHGPrBFSvSxjGkka7WsxBEpIUcntpkPg0SIPB0taQB5L3T2ct7IocFUosGC6VSLEdYIYpQFPX40TLnEg%3D%3D&Expires=1741792380 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 16:03:34,914 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9726566/d918352f-acfc-4d19-93b5-aa8602e50a11.json?AWSAccessKeyId=ASIAU3FAITLPWB7NJBZM&Signature=RYqVdvBp54IiTPu6W4b0%2BYh86c8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQCf0MIO6MLEjr21yK3YmkmHEyLKs0fLs55QzpkhopTYJAIgMdWcXo4V8pzFvC1Olu7BSoHTC2fChMiM5cx%2BfXhK9MUqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDCAuSmxhzkRiDUmsMirjAoD53jDUb5BrZ4biUXs55JlVUdq65nNQY7VQ99wbGt3Ph9%2Bux2GFWniZhUHKM92mTrtG0VApFeZ5t1ME596oFjsgUfJex81AvUdHX0EalU%2BbSXInPXex3Me4dLAXOuFWMpaSgbHUNyIL8q%2BAZDl55Nrgp%2FLxSh1arScVuApF%2BaUU18WalaJ2Mv60LC4RlBe7YL1FFmgKvO5JFJ0vZqb0kTkpjIodWG3znIg5W77gJYYgyhgMKvg8oGkjKBCTamPjLQG9werzRQPYl5ITNCh55hVlm8qnHo4GaFFntE52wGSL8mzpQUTPRIdBEhE%2F%2BGD64VFuQXNax3JCgW72Kd0%2FUbhUydQ6U1N%2Ba8%2BHcEqVjrkzrTA9UgT3kKzgMPBqxLWwsIkzfdUu%2FvpixggeD%2FS81%2BPvFO%2F3hQFX%2BMa56whuvmhA9M1ERDznULRic5FWlKIx0ZVsDlAc%2FClFCZLMsRFuFtumE9Iwh6zGvgY6ngFg52W605AFmCUtdxwGIlueNMP4jWOExZjSh2pkrOqhrmJ8SW2dPSVPuzWBItiRpMbaWpehr1hN8qnKMjk6TOwbelXcbfyZkJERPMYBOjkDyBjLzwEoF8Rah9n%2BPwDLcKQtNX4BWdOZlv9E%2F2FlJEGPjQMREr0LU53xqgc%2Boquy2YRDjCfSjcOdeCCYcfqBf4qY0fYaZtkY7VGqP%2BBSNw%3D%3D&Expires=1741792384
2025-03-12 16:03:35,035 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9726566/d918352f-acfc-4d19-93b5-aa8602e50a11.json?AWSAccessKeyId=ASIAU3FAITLPWB7NJBZM&Signature=RYqVdvBp54IiTPu6W4b0%2BYh86c8%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHYaCWV1LXdlc3QtMSJHMEUCIQCf0MIO6MLEjr21yK3YmkmHEyLKs0fLs55QzpkhopTYJAIgMdWcXo4V8pzFvC1Olu7BSoHTC2fChMiM5cx%2BfXhK9MUqjwMIv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARADGgwzMzMxOTYwNzM2OTUiDCAuSmxhzkRiDUmsMirjAoD53jDUb5BrZ4biUXs55JlVUdq65nNQY7VQ99wbGt3Ph9%2Bux2GFWniZhUHKM92mTrtG0VApFeZ5t1ME596oFjsgUfJex81AvUdHX0EalU%2BbSXInPXex3Me4dLAXOuFWMpaSgbHUNyIL8q%2BAZDl55Nrgp%2FLxSh1arScVuApF%2BaUU18WalaJ2Mv60LC4RlBe7YL1FFmgKvO5JFJ0vZqb0kTkpjIodWG3znIg5W77gJYYgyhgMKvg8oGkjKBCTamPjLQG9werzRQPYl5ITNCh55hVlm8qnHo4GaFFntE52wGSL8mzpQUTPRIdBEhE%2F%2BGD64VFuQXNax3JCgW72Kd0%2FUbhUydQ6U1N%2Ba8%2BHcEqVjrkzrTA9UgT3kKzgMPBqxLWwsIkzfdUu%2FvpixggeD%2FS81%2BPvFO%2F3hQFX%2BMa56whuvmhA9M1ERDznULRic5FWlKIx0ZVsDlAc%2FClFCZLMsRFuFtumE9Iwh6zGvgY6ngFg52W605AFmCUtdxwGIlueNMP4jWOExZjSh2pkrOqhrmJ8SW2dPSVPuzWBItiRpMbaWpehr1hN8qnKMjk6TOwbelXcbfyZkJERPMYBOjkDyBjLzwEoF8Rah9n%2BPwDLcKQtNX4BWdOZlv9E%2F2FlJEGPjQMREr0LU53xqgc%2Boquy2YRDjCfSjcOdeCCYcfqBf4qY0fYaZtkY7VGqP%2BBSNw%3D%3D&Expires=1741792384 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 16:03:38,128 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))': /fleet-api/timeseries/9693329/b7fa1681-b83a-405c-b028-60c8d2789cc4.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=hnVO3b2U5zEeXDxtNwg%2FPXckLqQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792387
2025-03-12 16:03:38,266 - hoppe_etl_pipeline - ERROR - API request failed: HTTPSConnectionPool(host='hm-prod-hda-temporary.s3.amazonaws.com', port=443): Max retries exceeded with url: /fleet-api/timeseries/9693329/b7fa1681-b83a-405c-b028-60c8d2789cc4.json?AWSAccessKeyId=ASIAU3FAITLPYCCNZNTY&Signature=hnVO3b2U5zEeXDxtNwg%2FPXckLqQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEHcaCWV1LXdlc3QtMSJIMEYCIQDTU%2Fwt%2B3zDG9zKtL%2F4zOLc9WZnIs1B99cmVZWdMcdjBQIhAIW2oPu1h0JdSsGIGIpF8G38EJZwFUj3iID9ZiuQFO%2BPKo8DCMD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQAxoMMzMzMTk2MDczNjk1Igy0h4QMqrVTf4HUK%2FYq4wJqT8C9b1z%2Bwf845%2FG2C9HDejfqecZJDW1HCf8yzHd7K0zogkPz20hdSITK%2F2yeFMv%2FtpB4K1DGjbvfy1GWn3hlb8TicavRLODbNVhlyubt%2FYbk05vYE%2B6u4CI4eZgJB8JpzpMCSI1ZHT6BuSXLaOggJTZ8xKbpatevi0iQU74dc%2BxQ1rF%2FhT8nQcq0Cbp7EF9JF%2FBnS9GHZ6KLy%2BEXflyoI7gNzhx59o7E4EUMnCn5Ji1Vo2B6EYHaGFVYi2wEQHBxy9Oxu9ELHoiIk%2FBkgTbD2YUTMEPOqhm6OMEplpxLgIjOLYhGy8s5CEdwFj5oA5uMajk77cVhH98tsDEskijx1cD9rnt9PVELiaUQjOU523zU83oPsnDvaZ5lv36DiZzYrOf0kThbtQGb9OmQNWKEVsLcFgWDAYxmc82ia3oIy%2BkCWZUbbV3xV4vHSaKd5JEoyJPN1L8uZsdEiUV25QsfKYYmMIPAxr4GOp0BidjnJ1HS4FALCCK5Ef%2Ba1dbeby8ZPkoHYh48AVWeM0RxDzeWxbC%2BLvNpchiZibjIL5UsVJ7p1xbWeLgOl72CJM44PBIbnM13EdjToOj6R60B4J5Fqw5m%2BrR0qyNmJvJ12xbNfnKK5s2qJ9QFXrSas4DY%2Fx1P9sjhYjos3gcx0PEKaJhIc0OvHOnRiXb4i8pxbJ8P7aQx9%2Bol4WBKlw%3D%3D&Expires=1741792387 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
2025-03-12 16:03:38,268 - hoppe_etl_pipeline - INFO - Cleanup of data older than 2024-12-12 completed
2025-03-12 16:03:38,271 - hoppe_etl_pipeline - INFO - Cleanup of data older than 2024-12-12 completed
2025-03-12 16:03:38,272 - hoppe_etl_pipeline - INFO - Cleanup of data older than 2024-12-12 completed
2025-03-12 16:03:38,273 - hoppe_etl_pipeline - INFO - Pipeline run completed successfully in 0:00:56.154535
2025-03-12 16:03:38,274 - hoppe_etl_pipeline - INFO - Pipeline completed in 0:00:56.155533
2025-03-12 16:03:38,276 - hoppe_etl_pipeline - INFO - Pipeline run completed at 2025/03/12/15/02
